# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/RWHitchins/Desktop/mandel/mandel_IP/mandel_IP.cache/wt [current_project]
set_property parent.project_path C:/Users/RWHitchins/Desktop/mandel/mandel_IP/mandel_IP.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths c:/users/rwhitchins/desktop/mandel [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/RWHitchins/Desktop/mandel/mandel_IP/mandel_IP.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library work {
  C:/Users/RWHitchins/Desktop/mandel/mandelbrot_tpg_top.vhd
  C:/Users/RWHitchins/Desktop/mandel/mandelbrot_tile.vhd
  C:/Users/RWHitchins/Desktop/mandel/mbrot_pkg.vhd
}
read_vhdl -library ieee_proposed C:/Users/RWHitchins/Desktop/mandel/fixed_pkg_c.vhd
read_vhdl -library ieee C:/Users/RWHitchins/Desktop/mandel/fixed_float_types_c.vhd
read_vhdl -library axi_lite_ipif_v3_0 {
  C:/Users/RWHitchins/Desktop/mandel/axi_lite_ipif_v3_0/axi_lite_ipif.vhd
  C:/Users/RWHitchins/Desktop/mandel/axi_lite_ipif_v3_0/address_decoder.vhd
  C:/Users/RWHitchins/Desktop/mandel/axi_lite_ipif_v3_0/ipif_pkg.vhd
  C:/Users/RWHitchins/Desktop/mandel/axi_lite_ipif_v3_0/slave_attachment.vhd
  C:/Users/RWHitchins/Desktop/mandel/axi_lite_ipif_v3_0/pselect_f.vhd
}
read_ip -quiet C:/Users/RWHitchins/Desktop/mandel/mandel_IP/mandel_IP.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/RWHitchins/Desktop/mandel/mandel_IP/mandel_IP.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top mandelbrot_tpg_top -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mandelbrot_tpg_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mandelbrot_tpg_top_utilization_synth.rpt -pb mandelbrot_tpg_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
