// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hdmi_test_v_tpg_0_0_tpgBackground (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        srcImg_V_val_0_V_dout,
        srcImg_V_val_0_V_empty_n,
        srcImg_V_val_0_V_read,
        srcImg_V_val_1_V_dout,
        srcImg_V_val_1_V_empty_n,
        srcImg_V_val_1_V_read,
        srcImg_V_val_2_V_dout,
        srcImg_V_val_2_V_empty_n,
        srcImg_V_val_2_V_read,
        height,
        width,
        passthruStartX,
        passthruStartY,
        passthruEndX,
        passthruEndY,
        enableInput,
        patternId,
        ZplateHorContStart,
        ZplateHorContDelta,
        ZplateVerContStart,
        ZplateVerContDelta,
        motionSpeed,
        colorFormat,
        outImg_V_val_0_V_din,
        outImg_V_val_0_V_full_n,
        outImg_V_val_0_V_write,
        outImg_V_val_1_V_din,
        outImg_V_val_1_V_full_n,
        outImg_V_val_1_V_write,
        outImg_V_val_2_V_din,
        outImg_V_val_2_V_full_n,
        outImg_V_val_2_V_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state8 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] srcImg_V_val_0_V_dout;
input   srcImg_V_val_0_V_empty_n;
output   srcImg_V_val_0_V_read;
input  [7:0] srcImg_V_val_1_V_dout;
input   srcImg_V_val_1_V_empty_n;
output   srcImg_V_val_1_V_read;
input  [7:0] srcImg_V_val_2_V_dout;
input   srcImg_V_val_2_V_empty_n;
output   srcImg_V_val_2_V_read;
input  [15:0] height;
input  [15:0] width;
input  [15:0] passthruStartX;
input  [15:0] passthruStartY;
input  [15:0] passthruEndX;
input  [15:0] passthruEndY;
input  [7:0] enableInput;
input  [7:0] patternId;
input  [15:0] ZplateHorContStart;
input  [15:0] ZplateHorContDelta;
input  [15:0] ZplateVerContStart;
input  [15:0] ZplateVerContDelta;
input  [7:0] motionSpeed;
input  [7:0] colorFormat;
output  [7:0] outImg_V_val_0_V_din;
input   outImg_V_val_0_V_full_n;
output   outImg_V_val_0_V_write;
output  [7:0] outImg_V_val_1_V_din;
input   outImg_V_val_1_V_full_n;
output   outImg_V_val_1_V_write;
output  [7:0] outImg_V_val_2_V_din;
input   outImg_V_val_2_V_full_n;
output   outImg_V_val_2_V_write;

reg ap_done;
reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [7:0] rampStart;
reg    srcImg_V_val_0_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond2_reg_1416;
reg   [0:0] exitcond2_reg_1416_pp0_iter1_reg;
wire   [0:0] tmp_fu_929_p2;
reg    srcImg_V_val_1_V_blk_n;
reg    srcImg_V_val_2_V_blk_n;
reg    outImg_V_val_0_V_blk_n;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] exitcond2_reg_1416_pp0_iter3_reg;
reg    outImg_V_val_1_V_blk_n;
reg    outImg_V_val_2_V_blk_n;
reg   [15:0] x_reg_465;
reg   [15:0] x_reg_465_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    srcImg_V_val_0_V0_status;
reg    ap_predicate_op63_read_state5;
reg    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
wire    outImg_V_val_0_V1_status;
reg    ap_block_state7_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
reg   [15:0] x_reg_465_pp0_iter2_reg;
wire   [7:0] patternId_read_read_fu_382_p2;
reg    ap_block_state1;
reg   [7:0] rampStart_load_reg_1387;
wire   [0:0] exitcond1_fu_939_p2;
wire    ap_CS_fsm_state2;
wire   [15:0] y_1_fu_944_p2;
reg   [15:0] y_1_reg_1401;
wire   [0:0] tmp_84_fu_950_p2;
reg   [0:0] tmp_84_reg_1406;
wire   [0:0] tmp_85_fu_955_p2;
reg   [0:0] tmp_85_reg_1411;
wire   [0:0] exitcond2_fu_970_p2;
reg   [0:0] exitcond2_reg_1416_pp0_iter2_reg;
wire   [15:0] x_1_fu_975_p2;
reg   [15:0] x_1_reg_1420;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_fu_986_p2;
reg   [0:0] or_cond_reg_1425;
reg   [0:0] or_cond_reg_1425_pp0_iter1_reg;
reg   [0:0] or_cond_reg_1425_pp0_iter2_reg;
reg   [0:0] or_cond_reg_1425_pp0_iter3_reg;
wire   [0:0] or_cond2_fu_996_p2;
reg   [0:0] or_cond2_reg_1429;
reg   [0:0] or_cond2_reg_1429_pp0_iter1_reg;
reg   [0:0] or_cond2_reg_1429_pp0_iter2_reg;
reg   [0:0] or_cond2_reg_1429_pp0_iter3_reg;
reg   [7:0] outpix_val_0_V_15_reg_1436;
reg   [7:0] outpix_val_1_V_20_reg_1442;
reg   [7:0] outpix_val_2_V_20_reg_1448;
reg   [7:0] outpix_val_0_V_17_reg_1499;
reg   [7:0] outpix_val_1_V_24_reg_1504;
reg   [7:0] outpix_val_2_V_24_reg_1509;
reg   [7:0] outpix_val_0_V_8_reg_1544;
reg   [7:0] outpix_val_1_V_21_reg_1549;
reg   [7:0] outpix_val_2_V_21_reg_1554;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter3;
wire    grp_tpgPatternRainbow_fu_667_ap_start;
wire    grp_tpgPatternRainbow_fu_667_ap_done;
wire    grp_tpgPatternRainbow_fu_667_ap_idle;
wire    grp_tpgPatternRainbow_fu_667_ap_ready;
reg    grp_tpgPatternRainbow_fu_667_ap_ce;
wire   [7:0] grp_tpgPatternRainbow_fu_667_ap_return_0;
wire   [7:0] grp_tpgPatternRainbow_fu_667_ap_return_1;
wire   [7:0] grp_tpgPatternRainbow_fu_667_ap_return_2;
reg    ap_predicate_op59_call_state4;
wire    ap_block_state3_pp0_stage0_iter0_ignore_call0;
wire    ap_block_state4_pp0_stage0_iter1_ignore_call0;
reg    ap_block_state5_pp0_stage0_iter2_ignore_call0;
wire    ap_block_state6_pp0_stage0_iter3_ignore_call0;
reg    ap_block_state7_pp0_stage0_iter4_ignore_call0;
reg    ap_block_pp0_stage0_11001_ignoreCallOp59;
wire    grp_tpgPatternCheckerBoa_fu_676_ap_start;
wire    grp_tpgPatternCheckerBoa_fu_676_ap_done;
wire    grp_tpgPatternCheckerBoa_fu_676_ap_idle;
wire    grp_tpgPatternCheckerBoa_fu_676_ap_ready;
reg    grp_tpgPatternCheckerBoa_fu_676_ap_ce;
wire   [7:0] grp_tpgPatternCheckerBoa_fu_676_ap_return_0;
wire   [7:0] grp_tpgPatternCheckerBoa_fu_676_ap_return_1;
wire   [7:0] grp_tpgPatternCheckerBoa_fu_676_ap_return_2;
reg    ap_predicate_op58_call_state4;
reg    ap_block_pp0_stage0_11001_ignoreCallOp58;
wire    grp_tpgPatternTartanColo_fu_709_ap_start;
wire    grp_tpgPatternTartanColo_fu_709_ap_done;
wire    grp_tpgPatternTartanColo_fu_709_ap_idle;
wire    grp_tpgPatternTartanColo_fu_709_ap_ready;
reg    grp_tpgPatternTartanColo_fu_709_ap_ce;
wire   [7:0] grp_tpgPatternTartanColo_fu_709_ap_return_0;
wire   [7:0] grp_tpgPatternTartanColo_fu_709_ap_return_1;
wire   [7:0] grp_tpgPatternTartanColo_fu_709_ap_return_2;
reg    ap_predicate_op60_call_state4;
reg    ap_block_pp0_stage0_11001_ignoreCallOp60;
wire    grp_tpgPatternCrossHatch_fu_742_ap_start;
wire    grp_tpgPatternCrossHatch_fu_742_ap_done;
wire    grp_tpgPatternCrossHatch_fu_742_ap_idle;
wire    grp_tpgPatternCrossHatch_fu_742_ap_ready;
reg    grp_tpgPatternCrossHatch_fu_742_ap_ce;
wire   [7:0] grp_tpgPatternCrossHatch_fu_742_ap_return_0;
wire   [7:0] grp_tpgPatternCrossHatch_fu_742_ap_return_1;
wire   [7:0] grp_tpgPatternCrossHatch_fu_742_ap_return_2;
reg    ap_predicate_op85_call_state5;
reg    ap_block_pp0_stage0_11001_ignoreCallOp85;
wire    grp_tpgPatternZonePlate_fu_763_ap_start;
wire    grp_tpgPatternZonePlate_fu_763_ap_done;
wire    grp_tpgPatternZonePlate_fu_763_ap_idle;
wire    grp_tpgPatternZonePlate_fu_763_ap_ready;
reg    grp_tpgPatternZonePlate_fu_763_ap_ce;
wire   [7:0] grp_tpgPatternZonePlate_fu_763_ap_return_0;
wire   [7:0] grp_tpgPatternZonePlate_fu_763_ap_return_1;
wire   [7:0] grp_tpgPatternZonePlate_fu_763_ap_return_2;
reg    ap_predicate_op61_call_state4;
reg    ap_block_pp0_stage0_11001_ignoreCallOp61;
wire    grp_tpgPatternColorBars_fu_783_ap_start;
wire    grp_tpgPatternColorBars_fu_783_ap_done;
wire    grp_tpgPatternColorBars_fu_783_ap_idle;
wire    grp_tpgPatternColorBars_fu_783_ap_ready;
reg    grp_tpgPatternColorBars_fu_783_ap_ce;
wire   [7:0] grp_tpgPatternColorBars_fu_783_ap_return_0;
wire   [7:0] grp_tpgPatternColorBars_fu_783_ap_return_1;
wire   [7:0] grp_tpgPatternColorBars_fu_783_ap_return_2;
reg    ap_predicate_op88_call_state5;
reg    ap_block_pp0_stage0_11001_ignoreCallOp88;
wire    call_ret2_tpgPatternVerticalRa_fu_807_ap_start;
wire    call_ret2_tpgPatternVerticalRa_fu_807_ap_done;
wire    call_ret2_tpgPatternVerticalRa_fu_807_ap_idle;
wire    call_ret2_tpgPatternVerticalRa_fu_807_ap_ready;
wire   [7:0] call_ret2_tpgPatternVerticalRa_fu_807_ap_return_0;
wire   [7:0] call_ret2_tpgPatternVerticalRa_fu_807_ap_return_1;
wire   [7:0] call_ret2_tpgPatternVerticalRa_fu_807_ap_return_2;
reg    call_ret2_tpgPatternVerticalRa_fu_807_ap_ce;
reg    ap_predicate_op162_call_state6;
reg    ap_block_pp0_stage0_11001_ignoreCallOp162;
wire    call_ret13_tpgPatternVerticalHo_fu_819_ap_start;
wire    call_ret13_tpgPatternVerticalHo_fu_819_ap_done;
wire    call_ret13_tpgPatternVerticalHo_fu_819_ap_idle;
wire    call_ret13_tpgPatternVerticalHo_fu_819_ap_ready;
wire   [7:0] call_ret13_tpgPatternVerticalHo_fu_819_ap_return_0;
wire   [7:0] call_ret13_tpgPatternVerticalHo_fu_819_ap_return_1;
wire   [7:0] call_ret13_tpgPatternVerticalHo_fu_819_ap_return_2;
reg    call_ret13_tpgPatternVerticalHo_fu_819_ap_ce;
reg    ap_predicate_op110_call_state6;
reg    ap_block_pp0_stage0_11001_ignoreCallOp110;
wire    grp_tpgPatternSolidBlue_fu_831_ap_start;
wire    grp_tpgPatternSolidBlue_fu_831_ap_done;
wire    grp_tpgPatternSolidBlue_fu_831_ap_idle;
wire    grp_tpgPatternSolidBlue_fu_831_ap_ready;
reg    grp_tpgPatternSolidBlue_fu_831_ap_ce;
wire   [7:0] grp_tpgPatternSolidBlue_fu_831_ap_return_0;
wire   [7:0] grp_tpgPatternSolidBlue_fu_831_ap_return_1;
wire   [7:0] grp_tpgPatternSolidBlue_fu_831_ap_return_2;
reg    ap_predicate_op94_call_state5;
reg    ap_block_pp0_stage0_11001_ignoreCallOp94;
wire    grp_tpgPatternSolidGreen_fu_840_ap_start;
wire    grp_tpgPatternSolidGreen_fu_840_ap_done;
wire    grp_tpgPatternSolidGreen_fu_840_ap_idle;
wire    grp_tpgPatternSolidGreen_fu_840_ap_ready;
reg    grp_tpgPatternSolidGreen_fu_840_ap_ce;
wire   [7:0] grp_tpgPatternSolidGreen_fu_840_ap_return_0;
wire   [7:0] grp_tpgPatternSolidGreen_fu_840_ap_return_1;
wire   [7:0] grp_tpgPatternSolidGreen_fu_840_ap_return_2;
reg    ap_predicate_op95_call_state5;
reg    ap_block_pp0_stage0_11001_ignoreCallOp95;
wire    grp_tpgPatternSolidRed_fu_849_ap_start;
wire    grp_tpgPatternSolidRed_fu_849_ap_done;
wire    grp_tpgPatternSolidRed_fu_849_ap_idle;
wire    grp_tpgPatternSolidRed_fu_849_ap_ready;
reg    grp_tpgPatternSolidRed_fu_849_ap_ce;
wire   [7:0] grp_tpgPatternSolidRed_fu_849_ap_return_0;
wire   [7:0] grp_tpgPatternSolidRed_fu_849_ap_return_1;
wire   [7:0] grp_tpgPatternSolidRed_fu_849_ap_return_2;
reg    ap_predicate_op96_call_state5;
reg    ap_block_pp0_stage0_11001_ignoreCallOp96;
wire    grp_tpgPatternSolidWhite_fu_858_ap_start;
wire    grp_tpgPatternSolidWhite_fu_858_ap_done;
wire    grp_tpgPatternSolidWhite_fu_858_ap_idle;
wire    grp_tpgPatternSolidWhite_fu_858_ap_ready;
reg    grp_tpgPatternSolidWhite_fu_858_ap_ce;
wire   [7:0] grp_tpgPatternSolidWhite_fu_858_ap_return_0;
wire   [7:0] grp_tpgPatternSolidWhite_fu_858_ap_return_1;
reg    ap_predicate_op89_call_state5;
reg    ap_block_pp0_stage0_11001_ignoreCallOp89;
wire    grp_tpgPatternSolidBlack_fu_867_ap_start;
wire    grp_tpgPatternSolidBlack_fu_867_ap_done;
wire    grp_tpgPatternSolidBlack_fu_867_ap_idle;
wire    grp_tpgPatternSolidBlack_fu_867_ap_ready;
reg    grp_tpgPatternSolidBlack_fu_867_ap_ce;
wire   [7:0] grp_tpgPatternSolidBlack_fu_867_ap_return_0;
wire   [7:0] grp_tpgPatternSolidBlack_fu_867_ap_return_1;
reg    ap_predicate_op55_call_state4;
reg    ap_predicate_op56_call_state4;
reg    ap_predicate_op57_call_state4;
reg    ap_predicate_op62_call_state4;
reg    ap_block_pp0_stage0_11001_ignoreCallOp55;
wire    call_ret15_tpgPRBS_fu_876_ap_start;
wire    call_ret15_tpgPRBS_fu_876_ap_done;
wire    call_ret15_tpgPRBS_fu_876_ap_idle;
wire    call_ret15_tpgPRBS_fu_876_ap_ready;
wire   [7:0] call_ret15_tpgPRBS_fu_876_ap_return_0;
wire   [7:0] call_ret15_tpgPRBS_fu_876_ap_return_1;
wire   [7:0] call_ret15_tpgPRBS_fu_876_ap_return_2;
reg    call_ret15_tpgPRBS_fu_876_ap_ce;
reg    ap_predicate_op100_call_state6;
reg    ap_block_pp0_stage0_11001_ignoreCallOp100;
wire    call_ret1_tpgPatternHorizontal_fu_889_ap_start;
wire    call_ret1_tpgPatternHorizontal_fu_889_ap_done;
wire    call_ret1_tpgPatternHorizontal_fu_889_ap_idle;
wire    call_ret1_tpgPatternHorizontal_fu_889_ap_ready;
wire   [7:0] call_ret1_tpgPatternHorizontal_fu_889_ap_return_0;
wire   [7:0] call_ret1_tpgPatternHorizontal_fu_889_ap_return_1;
wire   [7:0] call_ret1_tpgPatternHorizontal_fu_889_ap_return_2;
reg    call_ret1_tpgPatternHorizontal_fu_889_ap_ce;
reg    ap_predicate_op167_call_state6;
reg    ap_block_pp0_stage0_11001_ignoreCallOp167;
wire    call_ret3_tpgPatternTemporalRa_fu_899_ap_ready;
wire   [7:0] call_ret3_tpgPatternTemporalRa_fu_899_ap_return_0;
wire   [7:0] call_ret3_tpgPatternTemporalRa_fu_899_ap_return_1;
wire   [7:0] call_ret3_tpgPatternTemporalRa_fu_899_ap_return_2;
reg   [15:0] y_reg_453;
wire    ap_CS_fsm_state8;
reg   [15:0] ap_phi_mux_x_phi_fu_469_p4;
reg   [7:0] ap_phi_mux_outpix_val_V_2_2_phi_fu_480_p42;
reg   [7:0] ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477;
wire   [7:0] ap_phi_reg_pp0_iter0_outpix_val_V_2_2_reg_477;
reg   [7:0] ap_phi_reg_pp0_iter1_outpix_val_V_2_2_reg_477;
reg   [7:0] ap_phi_reg_pp0_iter2_outpix_val_V_2_2_reg_477;
reg   [7:0] ap_phi_reg_pp0_iter3_outpix_val_V_2_2_reg_477;
reg   [7:0] ap_phi_mux_outpix_val_V_1_2_phi_fu_527_p42;
reg   [7:0] ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524;
wire   [7:0] ap_phi_reg_pp0_iter0_outpix_val_V_1_2_reg_524;
reg   [7:0] ap_phi_reg_pp0_iter1_outpix_val_V_1_2_reg_524;
reg   [7:0] ap_phi_reg_pp0_iter2_outpix_val_V_1_2_reg_524;
reg   [7:0] ap_phi_reg_pp0_iter3_outpix_val_V_1_2_reg_524;
reg   [7:0] ap_phi_mux_outpix_val_V_0_2_phi_fu_576_p42;
reg   [7:0] ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571;
wire   [7:0] ap_phi_reg_pp0_iter0_outpix_val_V_0_2_reg_571;
reg   [7:0] ap_phi_reg_pp0_iter1_outpix_val_V_0_2_reg_571;
reg   [7:0] ap_phi_reg_pp0_iter2_outpix_val_V_0_2_reg_571;
reg   [7:0] ap_phi_reg_pp0_iter3_outpix_val_V_0_2_reg_571;
reg   [7:0] ap_phi_mux_tmp_val_2_V_2_phi_fu_628_p6;
wire   [7:0] ap_phi_reg_pp0_iter4_tmp_val_2_V_2_reg_625;
wire   [7:0] pix_val_V_2_2_outpix_fu_1225_p3;
reg   [7:0] ap_phi_mux_tmp_val_1_V_2_phi_fu_642_p6;
wire   [7:0] ap_phi_reg_pp0_iter4_tmp_val_1_V_2_reg_639;
wire   [7:0] pix_val_V_1_2_outpix_fu_1232_p3;
reg   [7:0] ap_phi_mux_tmp_val_0_V_2_phi_fu_656_p6;
wire   [7:0] ap_phi_reg_pp0_iter4_tmp_val_0_V_2_reg_653;
wire   [7:0] pix_val_V_0_2_outpix_fu_1239_p3;
reg    grp_tpgPatternRainbow_fu_667_ap_start_reg;
reg    ap_predicate_op59_call_state4_state3;
reg    grp_tpgPatternCheckerBoa_fu_676_ap_start_reg;
reg    ap_predicate_op58_call_state4_state3;
reg    grp_tpgPatternTartanColo_fu_709_ap_start_reg;
reg    ap_predicate_op60_call_state4_state3;
reg    grp_tpgPatternCrossHatch_fu_742_ap_start_reg;
reg    ap_predicate_op85_call_state5_state4;
reg    grp_tpgPatternZonePlate_fu_763_ap_start_reg;
reg    ap_predicate_op61_call_state4_state3;
reg    grp_tpgPatternColorBars_fu_783_ap_start_reg;
reg    ap_predicate_op88_call_state5_state4;
reg    call_ret2_tpgPatternVerticalRa_fu_807_ap_start_reg;
reg    ap_predicate_op162_call_state6_state5;
reg    call_ret13_tpgPatternVerticalHo_fu_819_ap_start_reg;
reg    ap_predicate_op110_call_state6_state5;
reg    grp_tpgPatternSolidBlue_fu_831_ap_start_reg;
reg    ap_predicate_op94_call_state5_state4;
reg    grp_tpgPatternSolidGreen_fu_840_ap_start_reg;
reg    ap_predicate_op95_call_state5_state4;
reg    grp_tpgPatternSolidRed_fu_849_ap_start_reg;
reg    ap_predicate_op96_call_state5_state4;
reg    grp_tpgPatternSolidWhite_fu_858_ap_start_reg;
reg    ap_predicate_op89_call_state5_state4;
reg    grp_tpgPatternSolidBlack_fu_867_ap_start_reg;
reg    ap_predicate_op55_call_state4_state3;
reg    ap_predicate_op56_call_state4_state3;
reg    ap_predicate_op57_call_state4_state3;
reg    ap_predicate_op62_call_state4_state3;
reg    call_ret15_tpgPRBS_fu_876_ap_start_reg;
reg    ap_predicate_op100_call_state6_state5;
reg    call_ret1_tpgPatternHorizontal_fu_889_ap_start_reg;
reg    ap_predicate_op167_call_state6_state5;
reg    srcImg_V_val_0_V0_update;
reg    outImg_V_val_0_V1_update;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] tmp_s_fu_960_p2;
reg   [7:0] tmp_val_0_V_fu_322;
reg   [7:0] tmp_val_1_V_fu_326;
reg   [7:0] tmp_val_2_V_fu_330;
reg   [7:0] outpix_val_0_V_fu_334;
reg   [7:0] outpix_val_1_V_fu_338;
reg   [7:0] outpix_val_2_V_fu_342;
wire   [0:0] tmp_91_fu_981_p2;
wire   [0:0] tmp_92_fu_991_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_1784;
reg    ap_condition_104;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 rampStart = 8'd0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 grp_tpgPatternRainbow_fu_667_ap_start_reg = 1'b0;
#0 grp_tpgPatternCheckerBoa_fu_676_ap_start_reg = 1'b0;
#0 grp_tpgPatternTartanColo_fu_709_ap_start_reg = 1'b0;
#0 grp_tpgPatternCrossHatch_fu_742_ap_start_reg = 1'b0;
#0 grp_tpgPatternZonePlate_fu_763_ap_start_reg = 1'b0;
#0 grp_tpgPatternColorBars_fu_783_ap_start_reg = 1'b0;
#0 call_ret2_tpgPatternVerticalRa_fu_807_ap_start_reg = 1'b0;
#0 call_ret13_tpgPatternVerticalHo_fu_819_ap_start_reg = 1'b0;
#0 grp_tpgPatternSolidBlue_fu_831_ap_start_reg = 1'b0;
#0 grp_tpgPatternSolidGreen_fu_840_ap_start_reg = 1'b0;
#0 grp_tpgPatternSolidRed_fu_849_ap_start_reg = 1'b0;
#0 grp_tpgPatternSolidWhite_fu_858_ap_start_reg = 1'b0;
#0 grp_tpgPatternSolidBlack_fu_867_ap_start_reg = 1'b0;
#0 call_ret15_tpgPRBS_fu_876_ap_start_reg = 1'b0;
#0 call_ret1_tpgPatternHorizontal_fu_889_ap_start_reg = 1'b0;
end

hdmi_test_v_tpg_0_0_tpgPatternRainbow grp_tpgPatternRainbow_fu_667(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternRainbow_fu_667_ap_start),
    .ap_done(grp_tpgPatternRainbow_fu_667_ap_done),
    .ap_idle(grp_tpgPatternRainbow_fu_667_ap_idle),
    .ap_ready(grp_tpgPatternRainbow_fu_667_ap_ready),
    .ap_ce(grp_tpgPatternRainbow_fu_667_ap_ce),
    .x(x_reg_465),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternRainbow_fu_667_ap_return_0),
    .ap_return_1(grp_tpgPatternRainbow_fu_667_ap_return_1),
    .ap_return_2(grp_tpgPatternRainbow_fu_667_ap_return_2)
);

hdmi_test_v_tpg_0_0_tpgPatternCheckerBoa grp_tpgPatternCheckerBoa_fu_676(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternCheckerBoa_fu_676_ap_start),
    .ap_done(grp_tpgPatternCheckerBoa_fu_676_ap_done),
    .ap_idle(grp_tpgPatternCheckerBoa_fu_676_ap_idle),
    .ap_ready(grp_tpgPatternCheckerBoa_fu_676_ap_ready),
    .ap_ce(grp_tpgPatternCheckerBoa_fu_676_ap_ce),
    .y(y_reg_453),
    .x(x_reg_465),
    .width(width),
    .height(height),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternCheckerBoa_fu_676_ap_return_0),
    .ap_return_1(grp_tpgPatternCheckerBoa_fu_676_ap_return_1),
    .ap_return_2(grp_tpgPatternCheckerBoa_fu_676_ap_return_2)
);

hdmi_test_v_tpg_0_0_tpgPatternTartanColo grp_tpgPatternTartanColo_fu_709(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternTartanColo_fu_709_ap_start),
    .ap_done(grp_tpgPatternTartanColo_fu_709_ap_done),
    .ap_idle(grp_tpgPatternTartanColo_fu_709_ap_idle),
    .ap_ready(grp_tpgPatternTartanColo_fu_709_ap_ready),
    .ap_ce(grp_tpgPatternTartanColo_fu_709_ap_ce),
    .y(y_reg_453),
    .x(x_reg_465),
    .width(width),
    .height(height),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternTartanColo_fu_709_ap_return_0),
    .ap_return_1(grp_tpgPatternTartanColo_fu_709_ap_return_1),
    .ap_return_2(grp_tpgPatternTartanColo_fu_709_ap_return_2)
);

hdmi_test_v_tpg_0_0_tpgPatternCrossHatch grp_tpgPatternCrossHatch_fu_742(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternCrossHatch_fu_742_ap_start),
    .ap_done(grp_tpgPatternCrossHatch_fu_742_ap_done),
    .ap_idle(grp_tpgPatternCrossHatch_fu_742_ap_idle),
    .ap_ready(grp_tpgPatternCrossHatch_fu_742_ap_ready),
    .ap_ce(grp_tpgPatternCrossHatch_fu_742_ap_ce),
    .y(y_reg_453),
    .x(x_reg_465_pp0_iter1_reg),
    .width(width),
    .height(height),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternCrossHatch_fu_742_ap_return_0),
    .ap_return_1(grp_tpgPatternCrossHatch_fu_742_ap_return_1),
    .ap_return_2(grp_tpgPatternCrossHatch_fu_742_ap_return_2)
);

hdmi_test_v_tpg_0_0_tpgPatternZonePlate grp_tpgPatternZonePlate_fu_763(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternZonePlate_fu_763_ap_start),
    .ap_done(grp_tpgPatternZonePlate_fu_763_ap_done),
    .ap_idle(grp_tpgPatternZonePlate_fu_763_ap_idle),
    .ap_ready(grp_tpgPatternZonePlate_fu_763_ap_ready),
    .ap_ce(grp_tpgPatternZonePlate_fu_763_ap_ce),
    .y(y_reg_453),
    .x(x_reg_465),
    .rampStart(rampStart_load_reg_1387),
    .Zplate_Hor_Control_S(ZplateHorContStart),
    .Zplate_Hor_Control_D(ZplateHorContDelta),
    .Zplate_Ver_Control_S(ZplateVerContStart),
    .Zplate_Ver_Control_D(ZplateVerContDelta),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternZonePlate_fu_763_ap_return_0),
    .ap_return_1(grp_tpgPatternZonePlate_fu_763_ap_return_1),
    .ap_return_2(grp_tpgPatternZonePlate_fu_763_ap_return_2)
);

hdmi_test_v_tpg_0_0_tpgPatternColorBars grp_tpgPatternColorBars_fu_783(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternColorBars_fu_783_ap_start),
    .ap_done(grp_tpgPatternColorBars_fu_783_ap_done),
    .ap_idle(grp_tpgPatternColorBars_fu_783_ap_idle),
    .ap_ready(grp_tpgPatternColorBars_fu_783_ap_ready),
    .ap_ce(grp_tpgPatternColorBars_fu_783_ap_ce),
    .x(x_reg_465_pp0_iter1_reg),
    .width(width),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternColorBars_fu_783_ap_return_0),
    .ap_return_1(grp_tpgPatternColorBars_fu_783_ap_return_1),
    .ap_return_2(grp_tpgPatternColorBars_fu_783_ap_return_2)
);

hdmi_test_v_tpg_0_0_tpgPatternVerticalRa call_ret2_tpgPatternVerticalRa_fu_807(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ret2_tpgPatternVerticalRa_fu_807_ap_start),
    .ap_done(call_ret2_tpgPatternVerticalRa_fu_807_ap_done),
    .ap_idle(call_ret2_tpgPatternVerticalRa_fu_807_ap_idle),
    .ap_ready(call_ret2_tpgPatternVerticalRa_fu_807_ap_ready),
    .y(y_reg_453),
    .x(x_reg_465_pp0_iter2_reg),
    .rampStart(rampStart_load_reg_1387),
    .color(colorFormat),
    .ap_return_0(call_ret2_tpgPatternVerticalRa_fu_807_ap_return_0),
    .ap_return_1(call_ret2_tpgPatternVerticalRa_fu_807_ap_return_1),
    .ap_return_2(call_ret2_tpgPatternVerticalRa_fu_807_ap_return_2),
    .ap_ce(call_ret2_tpgPatternVerticalRa_fu_807_ap_ce)
);

hdmi_test_v_tpg_0_0_tpgPatternVerticalHo call_ret13_tpgPatternVerticalHo_fu_819(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ret13_tpgPatternVerticalHo_fu_819_ap_start),
    .ap_done(call_ret13_tpgPatternVerticalHo_fu_819_ap_done),
    .ap_idle(call_ret13_tpgPatternVerticalHo_fu_819_ap_idle),
    .ap_ready(call_ret13_tpgPatternVerticalHo_fu_819_ap_ready),
    .y(y_reg_453),
    .x(x_reg_465_pp0_iter2_reg),
    .rampStart(rampStart_load_reg_1387),
    .color(colorFormat),
    .ap_return_0(call_ret13_tpgPatternVerticalHo_fu_819_ap_return_0),
    .ap_return_1(call_ret13_tpgPatternVerticalHo_fu_819_ap_return_1),
    .ap_return_2(call_ret13_tpgPatternVerticalHo_fu_819_ap_return_2),
    .ap_ce(call_ret13_tpgPatternVerticalHo_fu_819_ap_ce)
);

hdmi_test_v_tpg_0_0_tpgPatternSolidBlue grp_tpgPatternSolidBlue_fu_831(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternSolidBlue_fu_831_ap_start),
    .ap_done(grp_tpgPatternSolidBlue_fu_831_ap_done),
    .ap_idle(grp_tpgPatternSolidBlue_fu_831_ap_idle),
    .ap_ready(grp_tpgPatternSolidBlue_fu_831_ap_ready),
    .ap_ce(grp_tpgPatternSolidBlue_fu_831_ap_ce),
    .x(x_reg_465_pp0_iter1_reg),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternSolidBlue_fu_831_ap_return_0),
    .ap_return_1(grp_tpgPatternSolidBlue_fu_831_ap_return_1),
    .ap_return_2(grp_tpgPatternSolidBlue_fu_831_ap_return_2)
);

hdmi_test_v_tpg_0_0_tpgPatternSolidGreen grp_tpgPatternSolidGreen_fu_840(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternSolidGreen_fu_840_ap_start),
    .ap_done(grp_tpgPatternSolidGreen_fu_840_ap_done),
    .ap_idle(grp_tpgPatternSolidGreen_fu_840_ap_idle),
    .ap_ready(grp_tpgPatternSolidGreen_fu_840_ap_ready),
    .ap_ce(grp_tpgPatternSolidGreen_fu_840_ap_ce),
    .x(x_reg_465_pp0_iter1_reg),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternSolidGreen_fu_840_ap_return_0),
    .ap_return_1(grp_tpgPatternSolidGreen_fu_840_ap_return_1),
    .ap_return_2(grp_tpgPatternSolidGreen_fu_840_ap_return_2)
);

hdmi_test_v_tpg_0_0_tpgPatternSolidRed grp_tpgPatternSolidRed_fu_849(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternSolidRed_fu_849_ap_start),
    .ap_done(grp_tpgPatternSolidRed_fu_849_ap_done),
    .ap_idle(grp_tpgPatternSolidRed_fu_849_ap_idle),
    .ap_ready(grp_tpgPatternSolidRed_fu_849_ap_ready),
    .ap_ce(grp_tpgPatternSolidRed_fu_849_ap_ce),
    .x(x_reg_465_pp0_iter1_reg),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternSolidRed_fu_849_ap_return_0),
    .ap_return_1(grp_tpgPatternSolidRed_fu_849_ap_return_1),
    .ap_return_2(grp_tpgPatternSolidRed_fu_849_ap_return_2)
);

hdmi_test_v_tpg_0_0_tpgPatternSolidWhite grp_tpgPatternSolidWhite_fu_858(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternSolidWhite_fu_858_ap_start),
    .ap_done(grp_tpgPatternSolidWhite_fu_858_ap_done),
    .ap_idle(grp_tpgPatternSolidWhite_fu_858_ap_idle),
    .ap_ready(grp_tpgPatternSolidWhite_fu_858_ap_ready),
    .ap_ce(grp_tpgPatternSolidWhite_fu_858_ap_ce),
    .x(x_reg_465_pp0_iter1_reg),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternSolidWhite_fu_858_ap_return_0),
    .ap_return_1(grp_tpgPatternSolidWhite_fu_858_ap_return_1)
);

hdmi_test_v_tpg_0_0_tpgPatternSolidBlack grp_tpgPatternSolidBlack_fu_867(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternSolidBlack_fu_867_ap_start),
    .ap_done(grp_tpgPatternSolidBlack_fu_867_ap_done),
    .ap_idle(grp_tpgPatternSolidBlack_fu_867_ap_idle),
    .ap_ready(grp_tpgPatternSolidBlack_fu_867_ap_ready),
    .ap_ce(grp_tpgPatternSolidBlack_fu_867_ap_ce),
    .x(x_reg_465),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternSolidBlack_fu_867_ap_return_0),
    .ap_return_1(grp_tpgPatternSolidBlack_fu_867_ap_return_1)
);

hdmi_test_v_tpg_0_0_tpgPRBS call_ret15_tpgPRBS_fu_876(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ret15_tpgPRBS_fu_876_ap_start),
    .ap_done(call_ret15_tpgPRBS_fu_876_ap_done),
    .ap_idle(call_ret15_tpgPRBS_fu_876_ap_idle),
    .ap_ready(call_ret15_tpgPRBS_fu_876_ap_ready),
    .x(x_reg_465_pp0_iter2_reg),
    .color(colorFormat),
    .ap_return_0(call_ret15_tpgPRBS_fu_876_ap_return_0),
    .ap_return_1(call_ret15_tpgPRBS_fu_876_ap_return_1),
    .ap_return_2(call_ret15_tpgPRBS_fu_876_ap_return_2),
    .ap_ce(call_ret15_tpgPRBS_fu_876_ap_ce)
);

hdmi_test_v_tpg_0_0_tpgPatternHorizontal call_ret1_tpgPatternHorizontal_fu_889(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ret1_tpgPatternHorizontal_fu_889_ap_start),
    .ap_done(call_ret1_tpgPatternHorizontal_fu_889_ap_done),
    .ap_idle(call_ret1_tpgPatternHorizontal_fu_889_ap_idle),
    .ap_ready(call_ret1_tpgPatternHorizontal_fu_889_ap_ready),
    .x(x_reg_465_pp0_iter2_reg),
    .rampStart(rampStart_load_reg_1387),
    .color(colorFormat),
    .ap_return_0(call_ret1_tpgPatternHorizontal_fu_889_ap_return_0),
    .ap_return_1(call_ret1_tpgPatternHorizontal_fu_889_ap_return_1),
    .ap_return_2(call_ret1_tpgPatternHorizontal_fu_889_ap_return_2),
    .ap_ce(call_ret1_tpgPatternHorizontal_fu_889_ap_ce)
);

hdmi_test_v_tpg_0_0_tpgPatternTemporalRa call_ret3_tpgPatternTemporalRa_fu_899(
    .ap_ready(call_ret3_tpgPatternTemporalRa_fu_899_ap_ready),
    .rampStart(rampStart_load_reg_1387),
    .color(colorFormat),
    .ap_return_0(call_ret3_tpgPatternTemporalRa_fu_899_ap_return_0),
    .ap_return_1(call_ret3_tpgPatternTemporalRa_fu_899_ap_return_1),
    .ap_return_2(call_ret3_tpgPatternTemporalRa_fu_899_ap_return_2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((exitcond1_fu_939_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (exitcond2_fu_970_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond1_fu_939_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if (((exitcond1_fu_939_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        call_ret13_tpgPatternVerticalHo_fu_819_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op110_call_state6_state5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            call_ret13_tpgPatternVerticalHo_fu_819_ap_start_reg <= 1'b1;
        end else if ((call_ret13_tpgPatternVerticalHo_fu_819_ap_ready == 1'b1)) begin
            call_ret13_tpgPatternVerticalHo_fu_819_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        call_ret15_tpgPRBS_fu_876_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op100_call_state6_state5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            call_ret15_tpgPRBS_fu_876_ap_start_reg <= 1'b1;
        end else if ((call_ret15_tpgPRBS_fu_876_ap_ready == 1'b1)) begin
            call_ret15_tpgPRBS_fu_876_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        call_ret1_tpgPatternHorizontal_fu_889_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op167_call_state6_state5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            call_ret1_tpgPatternHorizontal_fu_889_ap_start_reg <= 1'b1;
        end else if ((call_ret1_tpgPatternHorizontal_fu_889_ap_ready == 1'b1)) begin
            call_ret1_tpgPatternHorizontal_fu_889_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        call_ret2_tpgPatternVerticalRa_fu_807_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op162_call_state6_state5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            call_ret2_tpgPatternVerticalRa_fu_807_ap_start_reg <= 1'b1;
        end else if ((call_ret2_tpgPatternVerticalRa_fu_807_ap_ready == 1'b1)) begin
            call_ret2_tpgPatternVerticalRa_fu_807_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternCheckerBoa_fu_676_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op58_call_state4_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_tpgPatternCheckerBoa_fu_676_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternCheckerBoa_fu_676_ap_ready == 1'b1)) begin
            grp_tpgPatternCheckerBoa_fu_676_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternColorBars_fu_783_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op88_call_state5_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_tpgPatternColorBars_fu_783_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternColorBars_fu_783_ap_ready == 1'b1)) begin
            grp_tpgPatternColorBars_fu_783_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternCrossHatch_fu_742_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op85_call_state5_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_tpgPatternCrossHatch_fu_742_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternCrossHatch_fu_742_ap_ready == 1'b1)) begin
            grp_tpgPatternCrossHatch_fu_742_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternRainbow_fu_667_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op59_call_state4_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_tpgPatternRainbow_fu_667_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternRainbow_fu_667_ap_ready == 1'b1)) begin
            grp_tpgPatternRainbow_fu_667_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternSolidBlack_fu_867_ap_start_reg <= 1'b0;
    end else begin
        if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op62_call_state4_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op57_call_state4_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op56_call_state4_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op55_call_state4_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
            grp_tpgPatternSolidBlack_fu_867_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternSolidBlack_fu_867_ap_ready == 1'b1)) begin
            grp_tpgPatternSolidBlack_fu_867_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternSolidBlue_fu_831_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op94_call_state5_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_tpgPatternSolidBlue_fu_831_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternSolidBlue_fu_831_ap_ready == 1'b1)) begin
            grp_tpgPatternSolidBlue_fu_831_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternSolidGreen_fu_840_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op95_call_state5_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_tpgPatternSolidGreen_fu_840_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternSolidGreen_fu_840_ap_ready == 1'b1)) begin
            grp_tpgPatternSolidGreen_fu_840_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternSolidRed_fu_849_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op96_call_state5_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_tpgPatternSolidRed_fu_849_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternSolidRed_fu_849_ap_ready == 1'b1)) begin
            grp_tpgPatternSolidRed_fu_849_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternSolidWhite_fu_858_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op89_call_state5_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_tpgPatternSolidWhite_fu_858_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternSolidWhite_fu_858_ap_ready == 1'b1)) begin
            grp_tpgPatternSolidWhite_fu_858_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternTartanColo_fu_709_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op60_call_state4_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_tpgPatternTartanColo_fu_709_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternTartanColo_fu_709_ap_ready == 1'b1)) begin
            grp_tpgPatternTartanColo_fu_709_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternZonePlate_fu_763_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op61_call_state4_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_tpgPatternZonePlate_fu_763_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternZonePlate_fu_763_ap_ready == 1'b1)) begin
            grp_tpgPatternZonePlate_fu_763_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd7) & (1'b0 == ap_block_pp0_stage0_11001)) | ((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd17) & (1'b0 == ap_block_pp0_stage0_11001)) | ((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd18) & (1'b0 == ap_block_pp0_stage0_11001)) | ((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd19) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ap_phi_reg_pp0_iter3_outpix_val_V_0_2_reg_571 <= 8'd0;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_outpix_val_V_0_2_reg_571 <= ap_phi_reg_pp0_iter2_outpix_val_V_0_2_reg_571;
    end
end

always @ (posedge ap_clk) begin
    if ((((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd7) & (1'b0 == ap_block_pp0_stage0_11001)) | ((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd17) & (1'b0 == ap_block_pp0_stage0_11001)) | ((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd18) & (1'b0 == ap_block_pp0_stage0_11001)) | ((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd19) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ap_phi_reg_pp0_iter3_outpix_val_V_1_2_reg_524 <= grp_tpgPatternSolidBlack_fu_867_ap_return_0;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_outpix_val_V_1_2_reg_524 <= ap_phi_reg_pp0_iter2_outpix_val_V_1_2_reg_524;
    end
end

always @ (posedge ap_clk) begin
    if ((((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd7) & (1'b0 == ap_block_pp0_stage0_11001)) | ((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd17) & (1'b0 == ap_block_pp0_stage0_11001)) | ((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd18) & (1'b0 == ap_block_pp0_stage0_11001)) | ((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd19) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ap_phi_reg_pp0_iter3_outpix_val_V_2_2_reg_477 <= grp_tpgPatternSolidBlack_fu_867_ap_return_1;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_outpix_val_V_2_2_reg_477 <= ap_phi_reg_pp0_iter2_outpix_val_V_2_2_reg_477;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId_read_read_fu_382_p2 == 8'd0))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571 <= outpix_val_0_V_fu_334;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd1))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571 <= call_ret1_tpgPatternHorizontal_fu_889_ap_return_0;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd2))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571 <= call_ret2_tpgPatternVerticalRa_fu_807_ap_return_0;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId_read_read_fu_382_p2 == 8'd3))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571 <= call_ret3_tpgPatternTemporalRa_fu_899_ap_return_0;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd4))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571 <= grp_tpgPatternSolidRed_fu_849_ap_return_0;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd5))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571 <= grp_tpgPatternSolidGreen_fu_840_ap_return_0;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd6))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571 <= grp_tpgPatternSolidBlue_fu_831_ap_return_0;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd8))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571 <= 8'd255;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd9))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571 <= grp_tpgPatternColorBars_fu_783_ap_return_0;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd11))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571 <= grp_tpgPatternTartanColo_fu_709_ap_return_0;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd12))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571 <= grp_tpgPatternCrossHatch_fu_742_ap_return_0;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd14))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571 <= call_ret13_tpgPatternVerticalHo_fu_819_ap_return_0;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd15))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571 <= grp_tpgPatternCheckerBoa_fu_676_ap_return_0;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd16))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571 <= call_ret15_tpgPRBS_fu_876_ap_return_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571 <= ap_phi_reg_pp0_iter3_outpix_val_V_0_2_reg_571;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId_read_read_fu_382_p2 == 8'd0))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524 <= outpix_val_1_V_fu_338;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd1))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524 <= call_ret1_tpgPatternHorizontal_fu_889_ap_return_1;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd2))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524 <= call_ret2_tpgPatternVerticalRa_fu_807_ap_return_1;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId_read_read_fu_382_p2 == 8'd3))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524 <= call_ret3_tpgPatternTemporalRa_fu_899_ap_return_1;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd4))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524 <= grp_tpgPatternSolidRed_fu_849_ap_return_1;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd5))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524 <= grp_tpgPatternSolidGreen_fu_840_ap_return_1;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd6))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524 <= grp_tpgPatternSolidBlue_fu_831_ap_return_1;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd8))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524 <= grp_tpgPatternSolidWhite_fu_858_ap_return_0;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd9))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524 <= grp_tpgPatternColorBars_fu_783_ap_return_1;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd11))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524 <= grp_tpgPatternTartanColo_fu_709_ap_return_1;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd12))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524 <= grp_tpgPatternCrossHatch_fu_742_ap_return_1;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd14))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524 <= call_ret13_tpgPatternVerticalHo_fu_819_ap_return_1;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd15))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524 <= grp_tpgPatternCheckerBoa_fu_676_ap_return_1;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd16))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524 <= call_ret15_tpgPRBS_fu_876_ap_return_1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524 <= ap_phi_reg_pp0_iter3_outpix_val_V_1_2_reg_524;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId_read_read_fu_382_p2 == 8'd0))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477 <= outpix_val_2_V_fu_342;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd1))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477 <= call_ret1_tpgPatternHorizontal_fu_889_ap_return_2;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd2))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477 <= call_ret2_tpgPatternVerticalRa_fu_807_ap_return_2;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId_read_read_fu_382_p2 == 8'd3))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477 <= call_ret3_tpgPatternTemporalRa_fu_899_ap_return_2;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd4))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477 <= grp_tpgPatternSolidRed_fu_849_ap_return_2;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd5))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477 <= grp_tpgPatternSolidGreen_fu_840_ap_return_2;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd6))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477 <= grp_tpgPatternSolidBlue_fu_831_ap_return_2;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd8))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477 <= grp_tpgPatternSolidWhite_fu_858_ap_return_1;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd9))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477 <= grp_tpgPatternColorBars_fu_783_ap_return_2;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd11))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477 <= grp_tpgPatternTartanColo_fu_709_ap_return_2;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd12))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477 <= grp_tpgPatternCrossHatch_fu_742_ap_return_2;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd14))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477 <= call_ret13_tpgPatternVerticalHo_fu_819_ap_return_2;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd15))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477 <= grp_tpgPatternCheckerBoa_fu_676_ap_return_2;
        end else if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd16))) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477 <= call_ret15_tpgPRBS_fu_876_ap_return_2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477 <= ap_phi_reg_pp0_iter3_outpix_val_V_2_2_reg_477;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_reg_1416 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_reg_465 <= x_1_reg_1420;
    end else if (((exitcond1_fu_939_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        x_reg_465 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        y_reg_453 <= y_1_reg_1401;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_reg_453 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_outpix_val_V_0_2_reg_571 <= ap_phi_reg_pp0_iter0_outpix_val_V_0_2_reg_571;
        ap_phi_reg_pp0_iter1_outpix_val_V_1_2_reg_524 <= ap_phi_reg_pp0_iter0_outpix_val_V_1_2_reg_524;
        ap_phi_reg_pp0_iter1_outpix_val_V_2_2_reg_477 <= ap_phi_reg_pp0_iter0_outpix_val_V_2_2_reg_477;
        x_1_reg_1420 <= x_1_fu_975_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter2_outpix_val_V_0_2_reg_571 <= ap_phi_reg_pp0_iter1_outpix_val_V_0_2_reg_571;
        ap_phi_reg_pp0_iter2_outpix_val_V_1_2_reg_524 <= ap_phi_reg_pp0_iter1_outpix_val_V_1_2_reg_524;
        ap_phi_reg_pp0_iter2_outpix_val_V_2_2_reg_477 <= ap_phi_reg_pp0_iter1_outpix_val_V_2_2_reg_477;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond2_reg_1416 <= exitcond2_fu_970_p2;
        exitcond2_reg_1416_pp0_iter1_reg <= exitcond2_reg_1416;
        or_cond2_reg_1429_pp0_iter1_reg <= or_cond2_reg_1429;
        or_cond_reg_1425_pp0_iter1_reg <= or_cond_reg_1425;
        x_reg_465_pp0_iter1_reg <= x_reg_465;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        exitcond2_reg_1416_pp0_iter2_reg <= exitcond2_reg_1416_pp0_iter1_reg;
        exitcond2_reg_1416_pp0_iter3_reg <= exitcond2_reg_1416_pp0_iter2_reg;
        or_cond2_reg_1429_pp0_iter2_reg <= or_cond2_reg_1429_pp0_iter1_reg;
        or_cond2_reg_1429_pp0_iter3_reg <= or_cond2_reg_1429_pp0_iter2_reg;
        or_cond_reg_1425_pp0_iter2_reg <= or_cond_reg_1425_pp0_iter1_reg;
        or_cond_reg_1425_pp0_iter3_reg <= or_cond_reg_1425_pp0_iter2_reg;
        x_reg_465_pp0_iter2_reg <= x_reg_465_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_929_p2 == 1'd0) & (or_cond_fu_986_p2 == 1'd0) & (exitcond2_fu_970_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        or_cond2_reg_1429 <= or_cond2_fu_996_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_929_p2 == 1'd0) & (exitcond2_fu_970_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        or_cond_reg_1425 <= or_cond_fu_986_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outpix_val_0_V_15_reg_1436 <= outpix_val_0_V_fu_334;
        outpix_val_1_V_20_reg_1442 <= outpix_val_1_V_fu_338;
        outpix_val_2_V_20_reg_1448 <= outpix_val_2_V_fu_342;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd13) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outpix_val_0_V_17_reg_1499 <= grp_tpgPatternRainbow_fu_667_ap_return_0;
        outpix_val_1_V_24_reg_1504 <= grp_tpgPatternRainbow_fu_667_ap_return_1;
        outpix_val_2_V_24_reg_1509 <= grp_tpgPatternRainbow_fu_667_ap_return_2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd10) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outpix_val_0_V_8_reg_1544 <= grp_tpgPatternZonePlate_fu_763_ap_return_0;
        outpix_val_1_V_21_reg_1549 <= grp_tpgPatternZonePlate_fu_763_ap_return_1;
        outpix_val_2_V_21_reg_1554 <= grp_tpgPatternZonePlate_fu_763_ap_return_2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_929_p2 == 1'd0) & (exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outpix_val_0_V_fu_334 <= srcImg_V_val_0_V_dout;
        outpix_val_1_V_fu_338 <= srcImg_V_val_1_V_dout;
        outpix_val_2_V_fu_342 <= srcImg_V_val_2_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_939_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        rampStart <= tmp_s_fu_960_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampStart_load_reg_1387 <= rampStart;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_939_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_84_reg_1406 <= tmp_84_fu_950_p2;
        tmp_85_reg_1411 <= tmp_85_fu_955_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_val_0_V_fu_322 <= ap_phi_mux_tmp_val_0_V_2_phi_fu_656_p6;
        tmp_val_1_V_fu_326 <= ap_phi_mux_tmp_val_1_V_2_phi_fu_642_p6;
        tmp_val_2_V_fu_330 <= ap_phi_mux_tmp_val_2_V_2_phi_fu_628_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        y_1_reg_1401 <= y_1_fu_944_p2;
    end
end

always @ (*) begin
    if (((exitcond1_fu_939_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_104)) begin
        if ((patternId == 8'd10)) begin
            ap_phi_mux_outpix_val_V_0_2_phi_fu_576_p42 = outpix_val_0_V_8_reg_1544;
        end else if ((patternId == 8'd13)) begin
            ap_phi_mux_outpix_val_V_0_2_phi_fu_576_p42 = outpix_val_0_V_17_reg_1499;
        end else if ((1'b1 == ap_condition_1784)) begin
            ap_phi_mux_outpix_val_V_0_2_phi_fu_576_p42 = tmp_val_0_V_fu_322;
        end else begin
            ap_phi_mux_outpix_val_V_0_2_phi_fu_576_p42 = ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571;
        end
    end else begin
        ap_phi_mux_outpix_val_V_0_2_phi_fu_576_p42 = ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_104)) begin
        if ((patternId == 8'd10)) begin
            ap_phi_mux_outpix_val_V_1_2_phi_fu_527_p42 = outpix_val_1_V_21_reg_1549;
        end else if ((patternId == 8'd13)) begin
            ap_phi_mux_outpix_val_V_1_2_phi_fu_527_p42 = outpix_val_1_V_24_reg_1504;
        end else if ((1'b1 == ap_condition_1784)) begin
            ap_phi_mux_outpix_val_V_1_2_phi_fu_527_p42 = tmp_val_1_V_fu_326;
        end else begin
            ap_phi_mux_outpix_val_V_1_2_phi_fu_527_p42 = ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524;
        end
    end else begin
        ap_phi_mux_outpix_val_V_1_2_phi_fu_527_p42 = ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_104)) begin
        if ((patternId == 8'd10)) begin
            ap_phi_mux_outpix_val_V_2_2_phi_fu_480_p42 = outpix_val_2_V_21_reg_1554;
        end else if ((patternId == 8'd13)) begin
            ap_phi_mux_outpix_val_V_2_2_phi_fu_480_p42 = outpix_val_2_V_24_reg_1509;
        end else if ((1'b1 == ap_condition_1784)) begin
            ap_phi_mux_outpix_val_V_2_2_phi_fu_480_p42 = tmp_val_2_V_fu_330;
        end else begin
            ap_phi_mux_outpix_val_V_2_2_phi_fu_480_p42 = ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477;
        end
    end else begin
        ap_phi_mux_outpix_val_V_2_2_phi_fu_480_p42 = ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477;
    end
end

always @ (*) begin
    if (((tmp_fu_929_p2 == 1'd0) & (or_cond_reg_1425_pp0_iter3_reg == 1'd0) & (exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_phi_mux_tmp_val_0_V_2_phi_fu_656_p6 = pix_val_V_0_2_outpix_fu_1239_p3;
    end else if ((((tmp_fu_929_p2 == 1'd0) & (exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (or_cond_reg_1425_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((tmp_fu_929_p2 == 1'd1) & (exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
        ap_phi_mux_tmp_val_0_V_2_phi_fu_656_p6 = ap_phi_mux_outpix_val_V_0_2_phi_fu_576_p42;
    end else begin
        ap_phi_mux_tmp_val_0_V_2_phi_fu_656_p6 = ap_phi_reg_pp0_iter4_tmp_val_0_V_2_reg_653;
    end
end

always @ (*) begin
    if (((tmp_fu_929_p2 == 1'd0) & (or_cond_reg_1425_pp0_iter3_reg == 1'd0) & (exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_phi_mux_tmp_val_1_V_2_phi_fu_642_p6 = pix_val_V_1_2_outpix_fu_1232_p3;
    end else if ((((tmp_fu_929_p2 == 1'd0) & (exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (or_cond_reg_1425_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((tmp_fu_929_p2 == 1'd1) & (exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
        ap_phi_mux_tmp_val_1_V_2_phi_fu_642_p6 = ap_phi_mux_outpix_val_V_1_2_phi_fu_527_p42;
    end else begin
        ap_phi_mux_tmp_val_1_V_2_phi_fu_642_p6 = ap_phi_reg_pp0_iter4_tmp_val_1_V_2_reg_639;
    end
end

always @ (*) begin
    if (((tmp_fu_929_p2 == 1'd0) & (or_cond_reg_1425_pp0_iter3_reg == 1'd0) & (exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_phi_mux_tmp_val_2_V_2_phi_fu_628_p6 = pix_val_V_2_2_outpix_fu_1225_p3;
    end else if ((((tmp_fu_929_p2 == 1'd0) & (exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (or_cond_reg_1425_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((tmp_fu_929_p2 == 1'd1) & (exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
        ap_phi_mux_tmp_val_2_V_2_phi_fu_628_p6 = ap_phi_mux_outpix_val_V_2_2_phi_fu_480_p42;
    end else begin
        ap_phi_mux_tmp_val_2_V_2_phi_fu_628_p6 = ap_phi_reg_pp0_iter4_tmp_val_2_V_2_reg_625;
    end
end

always @ (*) begin
    if (((exitcond2_reg_1416 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_x_phi_fu_469_p4 = x_1_reg_1420;
    end else begin
        ap_phi_mux_x_phi_fu_469_p4 = x_reg_465;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp110) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        call_ret13_tpgPatternVerticalHo_fu_819_ap_ce = 1'b1;
    end else begin
        call_ret13_tpgPatternVerticalHo_fu_819_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp100) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        call_ret15_tpgPRBS_fu_876_ap_ce = 1'b1;
    end else begin
        call_ret15_tpgPRBS_fu_876_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp167) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        call_ret1_tpgPatternHorizontal_fu_889_ap_ce = 1'b1;
    end else begin
        call_ret1_tpgPatternHorizontal_fu_889_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp162) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        call_ret2_tpgPatternVerticalRa_fu_807_ap_ce = 1'b1;
    end else begin
        call_ret2_tpgPatternVerticalRa_fu_807_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp58) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternCheckerBoa_fu_676_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternCheckerBoa_fu_676_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp88) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternColorBars_fu_783_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternColorBars_fu_783_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp85) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternCrossHatch_fu_742_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternCrossHatch_fu_742_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp59) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternRainbow_fu_667_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternRainbow_fu_667_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp55) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternSolidBlack_fu_867_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternSolidBlack_fu_867_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp94) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternSolidBlue_fu_831_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternSolidBlue_fu_831_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp95) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternSolidGreen_fu_840_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternSolidGreen_fu_840_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp96) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternSolidRed_fu_849_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternSolidRed_fu_849_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp89) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternSolidWhite_fu_858_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternSolidWhite_fu_858_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp60) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternTartanColo_fu_709_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternTartanColo_fu_709_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp61) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternZonePlate_fu_763_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternZonePlate_fu_763_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_fu_939_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outImg_V_val_0_V1_update = 1'b1;
    end else begin
        outImg_V_val_0_V1_update = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        outImg_V_val_0_V_blk_n = outImg_V_val_0_V_full_n;
    end else begin
        outImg_V_val_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        outImg_V_val_1_V_blk_n = outImg_V_val_1_V_full_n;
    end else begin
        outImg_V_val_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        outImg_V_val_2_V_blk_n = outImg_V_val_2_V_full_n;
    end else begin
        outImg_V_val_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op63_read_state5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        srcImg_V_val_0_V0_update = 1'b1;
    end else begin
        srcImg_V_val_0_V0_update = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_929_p2 == 1'd0) & (exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        srcImg_V_val_0_V_blk_n = srcImg_V_val_0_V_empty_n;
    end else begin
        srcImg_V_val_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_fu_929_p2 == 1'd0) & (exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        srcImg_V_val_1_V_blk_n = srcImg_V_val_1_V_empty_n;
    end else begin
        srcImg_V_val_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_fu_929_p2 == 1'd0) & (exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        srcImg_V_val_2_V_blk_n = srcImg_V_val_2_V_empty_n;
    end else begin
        srcImg_V_val_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond1_fu_939_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op63_read_state5 == 1'b1)) | ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op63_read_state5 == 1'b1)) | ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp100 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op63_read_state5 == 1'b1)) | ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp110 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op63_read_state5 == 1'b1)) | ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp162 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op63_read_state5 == 1'b1)) | ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp167 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op63_read_state5 == 1'b1)) | ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp55 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op63_read_state5 == 1'b1)) | ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp58 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op63_read_state5 == 1'b1)) | ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp59 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op63_read_state5 == 1'b1)) | ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp60 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op63_read_state5 == 1'b1)) | ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp61 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op63_read_state5 == 1'b1)) | ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp85 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op63_read_state5 == 1'b1)) | ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp88 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op63_read_state5 == 1'b1)) | ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp89 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op63_read_state5 == 1'b1)) | ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp94 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op63_read_state5 == 1'b1)) | ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp95 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op63_read_state5 == 1'b1)) | ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp96 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op63_read_state5 == 1'b1)) | ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op63_read_state5 == 1'b1)) | ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1_ignore_call0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter2 = ((srcImg_V_val_0_V0_status == 1'b0) & (ap_predicate_op63_read_state5 == 1'b1));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter2_ignore_call0 = ((srcImg_V_val_0_V0_status == 1'b0) & (ap_predicate_op63_read_state5 == 1'b1));
end

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter3_ignore_call0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter4 = ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0));
end

always @ (*) begin
    ap_block_state7_pp0_stage0_iter4_ignore_call0 = ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0));
end

always @ (*) begin
    ap_condition_104 = ((exitcond2_reg_1416_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1784 = (~(patternId_read_read_fu_382_p2 == 8'd0) & ~(patternId == 8'd1) & ~(patternId == 8'd2) & ~(patternId_read_read_fu_382_p2 == 8'd3) & ~(patternId == 8'd4) & ~(patternId == 8'd5) & ~(patternId == 8'd6) & ~(patternId == 8'd8) & ~(patternId == 8'd9) & ~(patternId == 8'd10) & ~(patternId == 8'd11) & ~(patternId == 8'd12) & ~(patternId == 8'd13) & ~(patternId == 8'd14) & ~(patternId == 8'd15) & ~(patternId == 8'd16) & ~(patternId == 8'd7) & ~(patternId == 8'd17) & ~(patternId == 8'd18) & ~(patternId == 8'd19));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_outpix_val_V_0_2_reg_571 = 'bx;

assign ap_phi_reg_pp0_iter0_outpix_val_V_1_2_reg_524 = 'bx;

assign ap_phi_reg_pp0_iter0_outpix_val_V_2_2_reg_477 = 'bx;

assign ap_phi_reg_pp0_iter4_tmp_val_0_V_2_reg_653 = 'bx;

assign ap_phi_reg_pp0_iter4_tmp_val_1_V_2_reg_639 = 'bx;

assign ap_phi_reg_pp0_iter4_tmp_val_2_V_2_reg_625 = 'bx;

always @ (*) begin
    ap_predicate_op100_call_state6 = ((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd16));
end

always @ (*) begin
    ap_predicate_op100_call_state6_state5 = ((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (patternId == 8'd16));
end

always @ (*) begin
    ap_predicate_op110_call_state6 = ((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd14));
end

always @ (*) begin
    ap_predicate_op110_call_state6_state5 = ((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (patternId == 8'd14));
end

always @ (*) begin
    ap_predicate_op162_call_state6 = ((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd2));
end

always @ (*) begin
    ap_predicate_op162_call_state6_state5 = ((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (patternId == 8'd2));
end

always @ (*) begin
    ap_predicate_op167_call_state6 = ((exitcond2_reg_1416_pp0_iter2_reg == 1'd0) & (patternId == 8'd1));
end

always @ (*) begin
    ap_predicate_op167_call_state6_state5 = ((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (patternId == 8'd1));
end

always @ (*) begin
    ap_predicate_op55_call_state4 = ((exitcond2_reg_1416 == 1'd0) & (patternId == 8'd19));
end

always @ (*) begin
    ap_predicate_op55_call_state4_state3 = ((exitcond2_fu_970_p2 == 1'd0) & (patternId == 8'd19));
end

always @ (*) begin
    ap_predicate_op56_call_state4 = ((exitcond2_reg_1416 == 1'd0) & (patternId == 8'd18));
end

always @ (*) begin
    ap_predicate_op56_call_state4_state3 = ((exitcond2_fu_970_p2 == 1'd0) & (patternId == 8'd18));
end

always @ (*) begin
    ap_predicate_op57_call_state4 = ((exitcond2_reg_1416 == 1'd0) & (patternId == 8'd17));
end

always @ (*) begin
    ap_predicate_op57_call_state4_state3 = ((exitcond2_fu_970_p2 == 1'd0) & (patternId == 8'd17));
end

always @ (*) begin
    ap_predicate_op58_call_state4 = ((exitcond2_reg_1416 == 1'd0) & (patternId == 8'd15));
end

always @ (*) begin
    ap_predicate_op58_call_state4_state3 = ((exitcond2_fu_970_p2 == 1'd0) & (patternId == 8'd15));
end

always @ (*) begin
    ap_predicate_op59_call_state4 = ((exitcond2_reg_1416 == 1'd0) & (patternId == 8'd13));
end

always @ (*) begin
    ap_predicate_op59_call_state4_state3 = ((exitcond2_fu_970_p2 == 1'd0) & (patternId == 8'd13));
end

always @ (*) begin
    ap_predicate_op60_call_state4 = ((exitcond2_reg_1416 == 1'd0) & (patternId == 8'd11));
end

always @ (*) begin
    ap_predicate_op60_call_state4_state3 = ((exitcond2_fu_970_p2 == 1'd0) & (patternId == 8'd11));
end

always @ (*) begin
    ap_predicate_op61_call_state4 = ((exitcond2_reg_1416 == 1'd0) & (patternId == 8'd10));
end

always @ (*) begin
    ap_predicate_op61_call_state4_state3 = ((exitcond2_fu_970_p2 == 1'd0) & (patternId == 8'd10));
end

always @ (*) begin
    ap_predicate_op62_call_state4 = ((exitcond2_reg_1416 == 1'd0) & (patternId == 8'd7));
end

always @ (*) begin
    ap_predicate_op62_call_state4_state3 = ((exitcond2_fu_970_p2 == 1'd0) & (patternId == 8'd7));
end

always @ (*) begin
    ap_predicate_op63_read_state5 = ((tmp_fu_929_p2 == 1'd0) & (exitcond2_reg_1416_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op85_call_state5 = ((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (patternId == 8'd12));
end

always @ (*) begin
    ap_predicate_op85_call_state5_state4 = ((exitcond2_reg_1416 == 1'd0) & (patternId == 8'd12));
end

always @ (*) begin
    ap_predicate_op88_call_state5 = ((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (patternId == 8'd9));
end

always @ (*) begin
    ap_predicate_op88_call_state5_state4 = ((exitcond2_reg_1416 == 1'd0) & (patternId == 8'd9));
end

always @ (*) begin
    ap_predicate_op89_call_state5 = ((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (patternId == 8'd8));
end

always @ (*) begin
    ap_predicate_op89_call_state5_state4 = ((exitcond2_reg_1416 == 1'd0) & (patternId == 8'd8));
end

always @ (*) begin
    ap_predicate_op94_call_state5 = ((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (patternId == 8'd6));
end

always @ (*) begin
    ap_predicate_op94_call_state5_state4 = ((exitcond2_reg_1416 == 1'd0) & (patternId == 8'd6));
end

always @ (*) begin
    ap_predicate_op95_call_state5 = ((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (patternId == 8'd5));
end

always @ (*) begin
    ap_predicate_op95_call_state5_state4 = ((exitcond2_reg_1416 == 1'd0) & (patternId == 8'd5));
end

always @ (*) begin
    ap_predicate_op96_call_state5 = ((exitcond2_reg_1416_pp0_iter1_reg == 1'd0) & (patternId == 8'd4));
end

always @ (*) begin
    ap_predicate_op96_call_state5_state4 = ((exitcond2_reg_1416 == 1'd0) & (patternId == 8'd4));
end

assign ap_ready = internal_ap_ready;

assign call_ret13_tpgPatternVerticalHo_fu_819_ap_start = call_ret13_tpgPatternVerticalHo_fu_819_ap_start_reg;

assign call_ret15_tpgPRBS_fu_876_ap_start = call_ret15_tpgPRBS_fu_876_ap_start_reg;

assign call_ret1_tpgPatternHorizontal_fu_889_ap_start = call_ret1_tpgPatternHorizontal_fu_889_ap_start_reg;

assign call_ret2_tpgPatternVerticalRa_fu_807_ap_start = call_ret2_tpgPatternVerticalRa_fu_807_ap_start_reg;

assign exitcond1_fu_939_p2 = ((y_reg_453 == height) ? 1'b1 : 1'b0);

assign exitcond2_fu_970_p2 = ((ap_phi_mux_x_phi_fu_469_p4 == width) ? 1'b1 : 1'b0);

assign grp_tpgPatternCheckerBoa_fu_676_ap_start = grp_tpgPatternCheckerBoa_fu_676_ap_start_reg;

assign grp_tpgPatternColorBars_fu_783_ap_start = grp_tpgPatternColorBars_fu_783_ap_start_reg;

assign grp_tpgPatternCrossHatch_fu_742_ap_start = grp_tpgPatternCrossHatch_fu_742_ap_start_reg;

assign grp_tpgPatternRainbow_fu_667_ap_start = grp_tpgPatternRainbow_fu_667_ap_start_reg;

assign grp_tpgPatternSolidBlack_fu_867_ap_start = grp_tpgPatternSolidBlack_fu_867_ap_start_reg;

assign grp_tpgPatternSolidBlue_fu_831_ap_start = grp_tpgPatternSolidBlue_fu_831_ap_start_reg;

assign grp_tpgPatternSolidGreen_fu_840_ap_start = grp_tpgPatternSolidGreen_fu_840_ap_start_reg;

assign grp_tpgPatternSolidRed_fu_849_ap_start = grp_tpgPatternSolidRed_fu_849_ap_start_reg;

assign grp_tpgPatternSolidWhite_fu_858_ap_start = grp_tpgPatternSolidWhite_fu_858_ap_start_reg;

assign grp_tpgPatternTartanColo_fu_709_ap_start = grp_tpgPatternTartanColo_fu_709_ap_start_reg;

assign grp_tpgPatternZonePlate_fu_763_ap_start = grp_tpgPatternZonePlate_fu_763_ap_start_reg;

assign or_cond2_fu_996_p2 = (tmp_92_fu_991_p2 & tmp_85_reg_1411);

assign or_cond_fu_986_p2 = (tmp_91_fu_981_p2 | tmp_84_reg_1406);

assign outImg_V_val_0_V1_status = (outImg_V_val_2_V_full_n & outImg_V_val_1_V_full_n & outImg_V_val_0_V_full_n);

assign outImg_V_val_0_V_din = ap_phi_mux_tmp_val_0_V_2_phi_fu_656_p6;

assign outImg_V_val_0_V_write = outImg_V_val_0_V1_update;

assign outImg_V_val_1_V_din = ap_phi_mux_tmp_val_1_V_2_phi_fu_642_p6;

assign outImg_V_val_1_V_write = outImg_V_val_0_V1_update;

assign outImg_V_val_2_V_din = ap_phi_mux_tmp_val_2_V_2_phi_fu_628_p6;

assign outImg_V_val_2_V_write = outImg_V_val_0_V1_update;

assign patternId_read_read_fu_382_p2 = patternId;

assign pix_val_V_0_2_outpix_fu_1239_p3 = ((or_cond2_reg_1429_pp0_iter3_reg[0:0] === 1'b1) ? outpix_val_0_V_15_reg_1436 : ap_phi_mux_outpix_val_V_0_2_phi_fu_576_p42);

assign pix_val_V_1_2_outpix_fu_1232_p3 = ((or_cond2_reg_1429_pp0_iter3_reg[0:0] === 1'b1) ? outpix_val_1_V_20_reg_1442 : ap_phi_mux_outpix_val_V_1_2_phi_fu_527_p42);

assign pix_val_V_2_2_outpix_fu_1225_p3 = ((or_cond2_reg_1429_pp0_iter3_reg[0:0] === 1'b1) ? outpix_val_2_V_20_reg_1448 : ap_phi_mux_outpix_val_V_2_2_phi_fu_480_p42);

assign srcImg_V_val_0_V0_status = (srcImg_V_val_2_V_empty_n & srcImg_V_val_1_V_empty_n & srcImg_V_val_0_V_empty_n);

assign srcImg_V_val_0_V_read = srcImg_V_val_0_V0_update;

assign srcImg_V_val_1_V_read = srcImg_V_val_0_V0_update;

assign srcImg_V_val_2_V_read = srcImg_V_val_0_V0_update;

assign start_out = real_start;

assign tmp_84_fu_950_p2 = ((y_reg_453 < passthruStartY) ? 1'b1 : 1'b0);

assign tmp_85_fu_955_p2 = ((y_reg_453 < passthruEndY) ? 1'b1 : 1'b0);

assign tmp_91_fu_981_p2 = ((ap_phi_mux_x_phi_fu_469_p4 < passthruStartX) ? 1'b1 : 1'b0);

assign tmp_92_fu_991_p2 = ((ap_phi_mux_x_phi_fu_469_p4 < passthruEndX) ? 1'b1 : 1'b0);

assign tmp_fu_929_p2 = ((enableInput == 8'd0) ? 1'b1 : 1'b0);

assign tmp_s_fu_960_p2 = (rampStart_load_reg_1387 + motionSpeed);

assign x_1_fu_975_p2 = (ap_phi_mux_x_phi_fu_469_p4 + 16'd1);

assign y_1_fu_944_p2 = (y_reg_453 + 16'd1);

endmodule //hdmi_test_v_tpg_0_0_tpgBackground
