// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hdmi_test_v_tpg_0_0_tpgBackground (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        srcImg_V_val_0_V_dout,
        srcImg_V_val_0_V_empty_n,
        srcImg_V_val_0_V_read,
        srcImg_V_val_1_V_dout,
        srcImg_V_val_1_V_empty_n,
        srcImg_V_val_1_V_read,
        srcImg_V_val_2_V_dout,
        srcImg_V_val_2_V_empty_n,
        srcImg_V_val_2_V_read,
        height,
        width,
        passthruStartX,
        passthruStartY,
        passthruEndX,
        passthruEndY,
        enableInput,
        patternId,
        ZplateHorContStart,
        ZplateHorContDelta,
        ZplateVerContStart,
        ZplateVerContDelta,
        motionSpeed,
        colorFormat,
        outImg_V_val_0_V_din,
        outImg_V_val_0_V_full_n,
        outImg_V_val_0_V_write,
        outImg_V_val_1_V_din,
        outImg_V_val_1_V_full_n,
        outImg_V_val_1_V_write,
        outImg_V_val_2_V_din,
        outImg_V_val_2_V_full_n,
        outImg_V_val_2_V_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state11 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] srcImg_V_val_0_V_dout;
input   srcImg_V_val_0_V_empty_n;
output   srcImg_V_val_0_V_read;
input  [7:0] srcImg_V_val_1_V_dout;
input   srcImg_V_val_1_V_empty_n;
output   srcImg_V_val_1_V_read;
input  [7:0] srcImg_V_val_2_V_dout;
input   srcImg_V_val_2_V_empty_n;
output   srcImg_V_val_2_V_read;
input  [15:0] height;
input  [15:0] width;
input  [15:0] passthruStartX;
input  [15:0] passthruStartY;
input  [15:0] passthruEndX;
input  [15:0] passthruEndY;
input  [7:0] enableInput;
input  [7:0] patternId;
input  [15:0] ZplateHorContStart;
input  [15:0] ZplateHorContDelta;
input  [15:0] ZplateVerContStart;
input  [15:0] ZplateVerContDelta;
input  [7:0] motionSpeed;
input  [7:0] colorFormat;
output  [7:0] outImg_V_val_0_V_din;
input   outImg_V_val_0_V_full_n;
output   outImg_V_val_0_V_write;
output  [7:0] outImg_V_val_1_V_din;
input   outImg_V_val_1_V_full_n;
output   outImg_V_val_1_V_write;
output  [7:0] outImg_V_val_2_V_din;
input   outImg_V_val_2_V_full_n;
output   outImg_V_val_2_V_write;

reg ap_done;
reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [7:0] rampStart;
reg    srcImg_V_val_0_V_blk_n;
reg    ap_enable_reg_pp0_iter4;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond2_reg_1419;
reg   [0:0] exitcond2_reg_1419_pp0_iter3_reg;
wire   [0:0] tmp_fu_932_p2;
reg    srcImg_V_val_1_V_blk_n;
reg    srcImg_V_val_2_V_blk_n;
reg    outImg_V_val_0_V_blk_n;
reg    ap_enable_reg_pp0_iter7;
reg   [0:0] exitcond2_reg_1419_pp0_iter6_reg;
reg    outImg_V_val_1_V_blk_n;
reg    outImg_V_val_2_V_blk_n;
reg   [15:0] x_reg_465;
reg   [15:0] x_reg_465_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
wire    srcImg_V_val_0_V0_status;
reg    ap_predicate_op86_read_state7;
reg    ap_block_state7_pp0_stage0_iter4;
wire    ap_block_state8_pp0_stage0_iter5;
wire    ap_block_state9_pp0_stage0_iter6;
wire    outImg_V_val_0_V1_status;
reg    ap_block_state10_pp0_stage0_iter7;
reg    ap_block_pp0_stage0_11001;
reg   [15:0] x_reg_465_pp0_iter2_reg;
reg   [15:0] x_reg_465_pp0_iter3_reg;
reg   [15:0] x_reg_465_pp0_iter4_reg;
reg   [7:0] tmp_val_2_V_2_reg_625;
reg   [7:0] tmp_val_1_V_2_reg_640;
reg   [7:0] tmp_val_0_V_2_reg_655;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] exitcond2_reg_1419_pp0_iter1_reg;
wire   [7:0] patternId_read_read_fu_382_p2;
reg    ap_block_state1;
reg   [7:0] rampStart_load_reg_1390;
wire   [0:0] exitcond1_fu_942_p2;
wire    ap_CS_fsm_state2;
wire   [15:0] y_1_fu_947_p2;
reg   [15:0] y_1_reg_1404;
wire   [0:0] tmp_84_fu_953_p2;
reg   [0:0] tmp_84_reg_1409;
wire   [0:0] tmp_85_fu_958_p2;
reg   [0:0] tmp_85_reg_1414;
wire   [0:0] exitcond2_fu_973_p2;
reg   [0:0] exitcond2_reg_1419_pp0_iter2_reg;
reg   [0:0] exitcond2_reg_1419_pp0_iter4_reg;
reg   [0:0] exitcond2_reg_1419_pp0_iter5_reg;
wire   [15:0] x_1_fu_978_p2;
reg   [15:0] x_1_reg_1423;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_fu_989_p2;
reg   [0:0] or_cond_reg_1428;
reg   [0:0] or_cond_reg_1428_pp0_iter1_reg;
reg   [0:0] or_cond_reg_1428_pp0_iter2_reg;
reg   [0:0] or_cond_reg_1428_pp0_iter3_reg;
reg   [0:0] or_cond_reg_1428_pp0_iter4_reg;
reg   [0:0] or_cond_reg_1428_pp0_iter5_reg;
wire   [0:0] or_cond2_fu_999_p2;
reg   [0:0] or_cond2_reg_1432;
reg   [0:0] or_cond2_reg_1432_pp0_iter1_reg;
reg   [0:0] or_cond2_reg_1432_pp0_iter2_reg;
reg   [0:0] or_cond2_reg_1432_pp0_iter3_reg;
reg   [0:0] or_cond2_reg_1432_pp0_iter4_reg;
reg   [0:0] or_cond2_reg_1432_pp0_iter5_reg;
reg   [7:0] outpix_val_0_V_15_reg_1439;
reg   [7:0] outpix_val_1_V_20_reg_1445;
reg   [7:0] outpix_val_2_V_20_reg_1451;
reg   [7:0] outpix_val_0_V_8_reg_1547;
reg   [7:0] outpix_val_1_V_21_reg_1552;
reg   [7:0] outpix_val_2_V_21_reg_1557;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_condition_pp0_exit_iter6_state9;
wire    grp_tpgPatternRainbow_fu_670_ap_start;
wire    grp_tpgPatternRainbow_fu_670_ap_done;
wire    grp_tpgPatternRainbow_fu_670_ap_idle;
wire    grp_tpgPatternRainbow_fu_670_ap_ready;
reg    grp_tpgPatternRainbow_fu_670_ap_ce;
wire   [7:0] grp_tpgPatternRainbow_fu_670_ap_return_0;
wire   [7:0] grp_tpgPatternRainbow_fu_670_ap_return_1;
wire   [7:0] grp_tpgPatternRainbow_fu_670_ap_return_2;
reg    ap_predicate_op61_call_state4;
wire    ap_block_state3_pp0_stage0_iter0_ignore_call0;
wire    ap_block_state4_pp0_stage0_iter1_ignore_call0;
wire    ap_block_state5_pp0_stage0_iter2_ignore_call0;
wire    ap_block_state6_pp0_stage0_iter3_ignore_call0;
reg    ap_block_state7_pp0_stage0_iter4_ignore_call0;
wire    ap_block_state8_pp0_stage0_iter5_ignore_call0;
wire    ap_block_state9_pp0_stage0_iter6_ignore_call0;
reg    ap_block_state10_pp0_stage0_iter7_ignore_call0;
reg    ap_block_pp0_stage0_11001_ignoreCallOp61;
wire    grp_tpgPatternCheckerBoa_fu_679_ap_start;
wire    grp_tpgPatternCheckerBoa_fu_679_ap_done;
wire    grp_tpgPatternCheckerBoa_fu_679_ap_idle;
wire    grp_tpgPatternCheckerBoa_fu_679_ap_ready;
reg    grp_tpgPatternCheckerBoa_fu_679_ap_ce;
wire   [7:0] grp_tpgPatternCheckerBoa_fu_679_ap_return_0;
wire   [7:0] grp_tpgPatternCheckerBoa_fu_679_ap_return_1;
wire   [7:0] grp_tpgPatternCheckerBoa_fu_679_ap_return_2;
reg    ap_predicate_op82_call_state6;
reg    ap_block_pp0_stage0_11001_ignoreCallOp82;
wire    grp_tpgPatternTartanColo_fu_712_ap_start;
wire    grp_tpgPatternTartanColo_fu_712_ap_done;
wire    grp_tpgPatternTartanColo_fu_712_ap_idle;
wire    grp_tpgPatternTartanColo_fu_712_ap_ready;
reg    grp_tpgPatternTartanColo_fu_712_ap_ce;
wire   [7:0] grp_tpgPatternTartanColo_fu_712_ap_return_0;
wire   [7:0] grp_tpgPatternTartanColo_fu_712_ap_return_1;
wire   [7:0] grp_tpgPatternTartanColo_fu_712_ap_return_2;
reg    ap_predicate_op84_call_state6;
reg    ap_block_pp0_stage0_11001_ignoreCallOp84;
wire    grp_tpgPatternCrossHatch_fu_745_ap_start;
wire    grp_tpgPatternCrossHatch_fu_745_ap_done;
wire    grp_tpgPatternCrossHatch_fu_745_ap_idle;
wire    grp_tpgPatternCrossHatch_fu_745_ap_ready;
reg    grp_tpgPatternCrossHatch_fu_745_ap_ce;
wire   [7:0] grp_tpgPatternCrossHatch_fu_745_ap_return_0;
wire   [7:0] grp_tpgPatternCrossHatch_fu_745_ap_return_1;
wire   [7:0] grp_tpgPatternCrossHatch_fu_745_ap_return_2;
reg    ap_predicate_op96_call_state7;
reg    ap_block_pp0_stage0_11001_ignoreCallOp96;
wire    grp_tpgPatternZonePlate_fu_766_ap_start;
wire    grp_tpgPatternZonePlate_fu_766_ap_done;
wire    grp_tpgPatternZonePlate_fu_766_ap_idle;
wire    grp_tpgPatternZonePlate_fu_766_ap_ready;
reg    grp_tpgPatternZonePlate_fu_766_ap_ce;
wire   [7:0] grp_tpgPatternZonePlate_fu_766_ap_return_0;
wire   [7:0] grp_tpgPatternZonePlate_fu_766_ap_return_1;
wire   [7:0] grp_tpgPatternZonePlate_fu_766_ap_return_2;
reg    ap_predicate_op62_call_state4;
reg    ap_block_pp0_stage0_11001_ignoreCallOp62;
wire    grp_tpgPatternColorBars_fu_786_ap_start;
wire    grp_tpgPatternColorBars_fu_786_ap_done;
wire    grp_tpgPatternColorBars_fu_786_ap_idle;
wire    grp_tpgPatternColorBars_fu_786_ap_ready;
reg    grp_tpgPatternColorBars_fu_786_ap_ce;
wire   [7:0] grp_tpgPatternColorBars_fu_786_ap_return_0;
wire   [7:0] grp_tpgPatternColorBars_fu_786_ap_return_1;
wire   [7:0] grp_tpgPatternColorBars_fu_786_ap_return_2;
reg    ap_predicate_op99_call_state7;
reg    ap_block_pp0_stage0_11001_ignoreCallOp99;
wire    call_ret2_tpgPatternVerticalRa_fu_810_ap_start;
wire    call_ret2_tpgPatternVerticalRa_fu_810_ap_done;
wire    call_ret2_tpgPatternVerticalRa_fu_810_ap_idle;
wire    call_ret2_tpgPatternVerticalRa_fu_810_ap_ready;
wire   [7:0] call_ret2_tpgPatternVerticalRa_fu_810_ap_return_0;
wire   [7:0] call_ret2_tpgPatternVerticalRa_fu_810_ap_return_1;
wire   [7:0] call_ret2_tpgPatternVerticalRa_fu_810_ap_return_2;
reg    call_ret2_tpgPatternVerticalRa_fu_810_ap_ce;
reg    ap_predicate_op170_call_state8;
reg    ap_block_pp0_stage0_11001_ignoreCallOp170;
wire    call_ret13_tpgPatternVerticalHo_fu_822_ap_start;
wire    call_ret13_tpgPatternVerticalHo_fu_822_ap_done;
wire    call_ret13_tpgPatternVerticalHo_fu_822_ap_idle;
wire    call_ret13_tpgPatternVerticalHo_fu_822_ap_ready;
wire   [7:0] call_ret13_tpgPatternVerticalHo_fu_822_ap_return_0;
wire   [7:0] call_ret13_tpgPatternVerticalHo_fu_822_ap_return_1;
wire   [7:0] call_ret13_tpgPatternVerticalHo_fu_822_ap_return_2;
reg    call_ret13_tpgPatternVerticalHo_fu_822_ap_ce;
reg    ap_predicate_op117_call_state8;
reg    ap_block_pp0_stage0_11001_ignoreCallOp117;
wire    grp_tpgPatternSolidBlue_fu_834_ap_start;
wire    grp_tpgPatternSolidBlue_fu_834_ap_done;
wire    grp_tpgPatternSolidBlue_fu_834_ap_idle;
wire    grp_tpgPatternSolidBlue_fu_834_ap_ready;
reg    grp_tpgPatternSolidBlue_fu_834_ap_ce;
wire   [7:0] grp_tpgPatternSolidBlue_fu_834_ap_return_0;
wire   [7:0] grp_tpgPatternSolidBlue_fu_834_ap_return_1;
wire   [7:0] grp_tpgPatternSolidBlue_fu_834_ap_return_2;
reg    ap_predicate_op101_call_state7;
reg    ap_block_pp0_stage0_11001_ignoreCallOp101;
wire    grp_tpgPatternSolidGreen_fu_843_ap_start;
wire    grp_tpgPatternSolidGreen_fu_843_ap_done;
wire    grp_tpgPatternSolidGreen_fu_843_ap_idle;
wire    grp_tpgPatternSolidGreen_fu_843_ap_ready;
reg    grp_tpgPatternSolidGreen_fu_843_ap_ce;
wire   [7:0] grp_tpgPatternSolidGreen_fu_843_ap_return_0;
wire   [7:0] grp_tpgPatternSolidGreen_fu_843_ap_return_1;
wire   [7:0] grp_tpgPatternSolidGreen_fu_843_ap_return_2;
reg    ap_predicate_op102_call_state7;
reg    ap_block_pp0_stage0_11001_ignoreCallOp102;
wire    grp_tpgPatternSolidRed_fu_852_ap_start;
wire    grp_tpgPatternSolidRed_fu_852_ap_done;
wire    grp_tpgPatternSolidRed_fu_852_ap_idle;
wire    grp_tpgPatternSolidRed_fu_852_ap_ready;
reg    grp_tpgPatternSolidRed_fu_852_ap_ce;
wire   [7:0] grp_tpgPatternSolidRed_fu_852_ap_return_0;
wire   [7:0] grp_tpgPatternSolidRed_fu_852_ap_return_1;
wire   [7:0] grp_tpgPatternSolidRed_fu_852_ap_return_2;
reg    ap_predicate_op103_call_state7;
reg    ap_block_pp0_stage0_11001_ignoreCallOp103;
wire    grp_tpgPatternSolidWhite_fu_861_ap_start;
wire    grp_tpgPatternSolidWhite_fu_861_ap_done;
wire    grp_tpgPatternSolidWhite_fu_861_ap_idle;
wire    grp_tpgPatternSolidWhite_fu_861_ap_ready;
reg    grp_tpgPatternSolidWhite_fu_861_ap_ce;
wire   [7:0] grp_tpgPatternSolidWhite_fu_861_ap_return_0;
wire   [7:0] grp_tpgPatternSolidWhite_fu_861_ap_return_1;
reg    ap_predicate_op100_call_state7;
reg    ap_block_pp0_stage0_11001_ignoreCallOp100;
wire    grp_tpgPatternSolidBlack_fu_870_ap_start;
wire    grp_tpgPatternSolidBlack_fu_870_ap_done;
wire    grp_tpgPatternSolidBlack_fu_870_ap_idle;
wire    grp_tpgPatternSolidBlack_fu_870_ap_ready;
reg    grp_tpgPatternSolidBlack_fu_870_ap_ce;
wire   [7:0] grp_tpgPatternSolidBlack_fu_870_ap_return_0;
wire   [7:0] grp_tpgPatternSolidBlack_fu_870_ap_return_1;
reg    ap_predicate_op58_call_state4;
reg    ap_predicate_op59_call_state4;
reg    ap_predicate_op60_call_state4;
reg    ap_predicate_op63_call_state4;
reg    ap_block_pp0_stage0_11001_ignoreCallOp58;
wire    call_ret15_tpgPRBS_fu_879_ap_start;
wire    call_ret15_tpgPRBS_fu_879_ap_done;
wire    call_ret15_tpgPRBS_fu_879_ap_idle;
wire    call_ret15_tpgPRBS_fu_879_ap_ready;
wire   [7:0] call_ret15_tpgPRBS_fu_879_ap_return_0;
wire   [7:0] call_ret15_tpgPRBS_fu_879_ap_return_1;
wire   [7:0] call_ret15_tpgPRBS_fu_879_ap_return_2;
reg    call_ret15_tpgPRBS_fu_879_ap_ce;
reg    ap_predicate_op107_call_state8;
reg    ap_block_pp0_stage0_11001_ignoreCallOp107;
wire    call_ret1_tpgPatternHorizontal_fu_892_ap_start;
wire    call_ret1_tpgPatternHorizontal_fu_892_ap_done;
wire    call_ret1_tpgPatternHorizontal_fu_892_ap_idle;
wire    call_ret1_tpgPatternHorizontal_fu_892_ap_ready;
wire   [7:0] call_ret1_tpgPatternHorizontal_fu_892_ap_return_0;
wire   [7:0] call_ret1_tpgPatternHorizontal_fu_892_ap_return_1;
wire   [7:0] call_ret1_tpgPatternHorizontal_fu_892_ap_return_2;
reg    call_ret1_tpgPatternHorizontal_fu_892_ap_ce;
reg    ap_predicate_op175_call_state8;
reg    ap_block_pp0_stage0_11001_ignoreCallOp175;
wire    call_ret3_tpgPatternTemporalRa_fu_902_ap_ready;
wire   [7:0] call_ret3_tpgPatternTemporalRa_fu_902_ap_return_0;
wire   [7:0] call_ret3_tpgPatternTemporalRa_fu_902_ap_return_1;
wire   [7:0] call_ret3_tpgPatternTemporalRa_fu_902_ap_return_2;
reg   [15:0] y_reg_453;
wire    ap_CS_fsm_state11;
reg   [15:0] ap_phi_mux_x_phi_fu_469_p4;
reg   [7:0] ap_phi_mux_outpix_val_V_2_2_phi_fu_480_p42;
reg   [7:0] ap_phi_reg_pp0_iter6_outpix_val_V_2_2_reg_477;
wire   [7:0] ap_phi_reg_pp0_iter0_outpix_val_V_2_2_reg_477;
reg   [7:0] ap_phi_reg_pp0_iter1_outpix_val_V_2_2_reg_477;
reg   [7:0] ap_phi_reg_pp0_iter2_outpix_val_V_2_2_reg_477;
reg   [7:0] ap_phi_reg_pp0_iter3_outpix_val_V_2_2_reg_477;
reg   [7:0] ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477;
reg   [7:0] ap_phi_reg_pp0_iter5_outpix_val_V_2_2_reg_477;
reg   [7:0] ap_phi_mux_outpix_val_V_1_2_phi_fu_527_p42;
reg   [7:0] ap_phi_reg_pp0_iter6_outpix_val_V_1_2_reg_524;
wire   [7:0] ap_phi_reg_pp0_iter0_outpix_val_V_1_2_reg_524;
reg   [7:0] ap_phi_reg_pp0_iter1_outpix_val_V_1_2_reg_524;
reg   [7:0] ap_phi_reg_pp0_iter2_outpix_val_V_1_2_reg_524;
reg   [7:0] ap_phi_reg_pp0_iter3_outpix_val_V_1_2_reg_524;
reg   [7:0] ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524;
reg   [7:0] ap_phi_reg_pp0_iter5_outpix_val_V_1_2_reg_524;
reg   [7:0] ap_phi_mux_outpix_val_V_0_2_phi_fu_576_p42;
reg   [7:0] ap_phi_reg_pp0_iter6_outpix_val_V_0_2_reg_571;
wire   [7:0] ap_phi_reg_pp0_iter0_outpix_val_V_0_2_reg_571;
reg   [7:0] ap_phi_reg_pp0_iter1_outpix_val_V_0_2_reg_571;
reg   [7:0] ap_phi_reg_pp0_iter2_outpix_val_V_0_2_reg_571;
reg   [7:0] ap_phi_reg_pp0_iter3_outpix_val_V_0_2_reg_571;
reg   [7:0] ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571;
reg   [7:0] ap_phi_reg_pp0_iter5_outpix_val_V_0_2_reg_571;
reg   [7:0] ap_phi_mux_tmp_val_2_V_2_phi_fu_629_p6;
wire   [7:0] ap_phi_reg_pp0_iter6_tmp_val_2_V_2_reg_625;
wire   [7:0] pix_val_V_2_2_outpix_fu_1228_p3;
reg   [7:0] ap_phi_mux_tmp_val_1_V_2_phi_fu_644_p6;
wire   [7:0] ap_phi_reg_pp0_iter6_tmp_val_1_V_2_reg_640;
wire   [7:0] pix_val_V_1_2_outpix_fu_1235_p3;
reg   [7:0] ap_phi_mux_tmp_val_0_V_2_phi_fu_659_p6;
wire   [7:0] ap_phi_reg_pp0_iter6_tmp_val_0_V_2_reg_655;
wire   [7:0] pix_val_V_0_2_outpix_fu_1242_p3;
reg    grp_tpgPatternRainbow_fu_670_ap_start_reg;
reg    ap_predicate_op61_call_state4_state3;
reg    grp_tpgPatternCheckerBoa_fu_679_ap_start_reg;
reg    ap_predicate_op82_call_state6_state5;
reg    grp_tpgPatternTartanColo_fu_712_ap_start_reg;
reg    ap_predicate_op84_call_state6_state5;
reg    grp_tpgPatternCrossHatch_fu_745_ap_start_reg;
reg    ap_predicate_op96_call_state7_state6;
reg    grp_tpgPatternZonePlate_fu_766_ap_start_reg;
reg    ap_predicate_op62_call_state4_state3;
reg    grp_tpgPatternColorBars_fu_786_ap_start_reg;
reg    ap_predicate_op99_call_state7_state6;
reg    call_ret2_tpgPatternVerticalRa_fu_810_ap_start_reg;
reg    ap_predicate_op170_call_state8_state7;
reg    call_ret13_tpgPatternVerticalHo_fu_822_ap_start_reg;
reg    ap_predicate_op117_call_state8_state7;
reg    grp_tpgPatternSolidBlue_fu_834_ap_start_reg;
reg    ap_predicate_op101_call_state7_state6;
reg    grp_tpgPatternSolidGreen_fu_843_ap_start_reg;
reg    ap_predicate_op102_call_state7_state6;
reg    grp_tpgPatternSolidRed_fu_852_ap_start_reg;
reg    ap_predicate_op103_call_state7_state6;
reg    grp_tpgPatternSolidWhite_fu_861_ap_start_reg;
reg    ap_predicate_op100_call_state7_state6;
reg    grp_tpgPatternSolidBlack_fu_870_ap_start_reg;
reg    ap_predicate_op58_call_state4_state3;
reg    ap_predicate_op59_call_state4_state3;
reg    ap_predicate_op60_call_state4_state3;
reg    ap_predicate_op63_call_state4_state3;
reg    call_ret15_tpgPRBS_fu_879_ap_start_reg;
reg    ap_predicate_op107_call_state8_state7;
reg    call_ret1_tpgPatternHorizontal_fu_892_ap_start_reg;
reg    ap_predicate_op175_call_state8_state7;
reg    srcImg_V_val_0_V0_update;
reg    outImg_V_val_0_V1_update;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] tmp_s_fu_963_p2;
reg   [7:0] tmp_val_0_V_fu_322;
reg   [7:0] tmp_val_1_V_fu_326;
reg   [7:0] tmp_val_2_V_fu_330;
reg   [7:0] outpix_val_0_V_fu_334;
reg   [7:0] outpix_val_1_V_fu_338;
reg   [7:0] outpix_val_2_V_fu_342;
wire   [0:0] tmp_91_fu_984_p2;
wire   [0:0] tmp_92_fu_994_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_1849;
reg    ap_condition_1830;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 rampStart = 8'd0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 grp_tpgPatternRainbow_fu_670_ap_start_reg = 1'b0;
#0 grp_tpgPatternCheckerBoa_fu_679_ap_start_reg = 1'b0;
#0 grp_tpgPatternTartanColo_fu_712_ap_start_reg = 1'b0;
#0 grp_tpgPatternCrossHatch_fu_745_ap_start_reg = 1'b0;
#0 grp_tpgPatternZonePlate_fu_766_ap_start_reg = 1'b0;
#0 grp_tpgPatternColorBars_fu_786_ap_start_reg = 1'b0;
#0 call_ret2_tpgPatternVerticalRa_fu_810_ap_start_reg = 1'b0;
#0 call_ret13_tpgPatternVerticalHo_fu_822_ap_start_reg = 1'b0;
#0 grp_tpgPatternSolidBlue_fu_834_ap_start_reg = 1'b0;
#0 grp_tpgPatternSolidGreen_fu_843_ap_start_reg = 1'b0;
#0 grp_tpgPatternSolidRed_fu_852_ap_start_reg = 1'b0;
#0 grp_tpgPatternSolidWhite_fu_861_ap_start_reg = 1'b0;
#0 grp_tpgPatternSolidBlack_fu_870_ap_start_reg = 1'b0;
#0 call_ret15_tpgPRBS_fu_879_ap_start_reg = 1'b0;
#0 call_ret1_tpgPatternHorizontal_fu_892_ap_start_reg = 1'b0;
end

hdmi_test_v_tpg_0_0_tpgPatternRainbow grp_tpgPatternRainbow_fu_670(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternRainbow_fu_670_ap_start),
    .ap_done(grp_tpgPatternRainbow_fu_670_ap_done),
    .ap_idle(grp_tpgPatternRainbow_fu_670_ap_idle),
    .ap_ready(grp_tpgPatternRainbow_fu_670_ap_ready),
    .ap_ce(grp_tpgPatternRainbow_fu_670_ap_ce),
    .x(x_reg_465),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternRainbow_fu_670_ap_return_0),
    .ap_return_1(grp_tpgPatternRainbow_fu_670_ap_return_1),
    .ap_return_2(grp_tpgPatternRainbow_fu_670_ap_return_2)
);

hdmi_test_v_tpg_0_0_tpgPatternCheckerBoa grp_tpgPatternCheckerBoa_fu_679(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternCheckerBoa_fu_679_ap_start),
    .ap_done(grp_tpgPatternCheckerBoa_fu_679_ap_done),
    .ap_idle(grp_tpgPatternCheckerBoa_fu_679_ap_idle),
    .ap_ready(grp_tpgPatternCheckerBoa_fu_679_ap_ready),
    .ap_ce(grp_tpgPatternCheckerBoa_fu_679_ap_ce),
    .y(y_reg_453),
    .x(x_reg_465_pp0_iter2_reg),
    .width(width),
    .height(height),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternCheckerBoa_fu_679_ap_return_0),
    .ap_return_1(grp_tpgPatternCheckerBoa_fu_679_ap_return_1),
    .ap_return_2(grp_tpgPatternCheckerBoa_fu_679_ap_return_2)
);

hdmi_test_v_tpg_0_0_tpgPatternTartanColo grp_tpgPatternTartanColo_fu_712(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternTartanColo_fu_712_ap_start),
    .ap_done(grp_tpgPatternTartanColo_fu_712_ap_done),
    .ap_idle(grp_tpgPatternTartanColo_fu_712_ap_idle),
    .ap_ready(grp_tpgPatternTartanColo_fu_712_ap_ready),
    .ap_ce(grp_tpgPatternTartanColo_fu_712_ap_ce),
    .y(y_reg_453),
    .x(x_reg_465_pp0_iter2_reg),
    .width(width),
    .height(height),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternTartanColo_fu_712_ap_return_0),
    .ap_return_1(grp_tpgPatternTartanColo_fu_712_ap_return_1),
    .ap_return_2(grp_tpgPatternTartanColo_fu_712_ap_return_2)
);

hdmi_test_v_tpg_0_0_tpgPatternCrossHatch grp_tpgPatternCrossHatch_fu_745(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternCrossHatch_fu_745_ap_start),
    .ap_done(grp_tpgPatternCrossHatch_fu_745_ap_done),
    .ap_idle(grp_tpgPatternCrossHatch_fu_745_ap_idle),
    .ap_ready(grp_tpgPatternCrossHatch_fu_745_ap_ready),
    .ap_ce(grp_tpgPatternCrossHatch_fu_745_ap_ce),
    .y(y_reg_453),
    .x(x_reg_465_pp0_iter3_reg),
    .width(width),
    .height(height),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternCrossHatch_fu_745_ap_return_0),
    .ap_return_1(grp_tpgPatternCrossHatch_fu_745_ap_return_1),
    .ap_return_2(grp_tpgPatternCrossHatch_fu_745_ap_return_2)
);

hdmi_test_v_tpg_0_0_tpgPatternZonePlate grp_tpgPatternZonePlate_fu_766(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternZonePlate_fu_766_ap_start),
    .ap_done(grp_tpgPatternZonePlate_fu_766_ap_done),
    .ap_idle(grp_tpgPatternZonePlate_fu_766_ap_idle),
    .ap_ready(grp_tpgPatternZonePlate_fu_766_ap_ready),
    .ap_ce(grp_tpgPatternZonePlate_fu_766_ap_ce),
    .y(y_reg_453),
    .x(x_reg_465),
    .rampStart(rampStart_load_reg_1390),
    .Zplate_Hor_Control_S(ZplateHorContStart),
    .Zplate_Hor_Control_D(ZplateHorContDelta),
    .Zplate_Ver_Control_S(ZplateVerContStart),
    .Zplate_Ver_Control_D(ZplateVerContDelta),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternZonePlate_fu_766_ap_return_0),
    .ap_return_1(grp_tpgPatternZonePlate_fu_766_ap_return_1),
    .ap_return_2(grp_tpgPatternZonePlate_fu_766_ap_return_2)
);

hdmi_test_v_tpg_0_0_tpgPatternColorBars grp_tpgPatternColorBars_fu_786(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternColorBars_fu_786_ap_start),
    .ap_done(grp_tpgPatternColorBars_fu_786_ap_done),
    .ap_idle(grp_tpgPatternColorBars_fu_786_ap_idle),
    .ap_ready(grp_tpgPatternColorBars_fu_786_ap_ready),
    .ap_ce(grp_tpgPatternColorBars_fu_786_ap_ce),
    .x(x_reg_465_pp0_iter3_reg),
    .width(width),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternColorBars_fu_786_ap_return_0),
    .ap_return_1(grp_tpgPatternColorBars_fu_786_ap_return_1),
    .ap_return_2(grp_tpgPatternColorBars_fu_786_ap_return_2)
);

hdmi_test_v_tpg_0_0_tpgPatternVerticalRa call_ret2_tpgPatternVerticalRa_fu_810(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ret2_tpgPatternVerticalRa_fu_810_ap_start),
    .ap_done(call_ret2_tpgPatternVerticalRa_fu_810_ap_done),
    .ap_idle(call_ret2_tpgPatternVerticalRa_fu_810_ap_idle),
    .ap_ready(call_ret2_tpgPatternVerticalRa_fu_810_ap_ready),
    .y(y_reg_453),
    .x(x_reg_465_pp0_iter4_reg),
    .rampStart(rampStart_load_reg_1390),
    .color(colorFormat),
    .ap_return_0(call_ret2_tpgPatternVerticalRa_fu_810_ap_return_0),
    .ap_return_1(call_ret2_tpgPatternVerticalRa_fu_810_ap_return_1),
    .ap_return_2(call_ret2_tpgPatternVerticalRa_fu_810_ap_return_2),
    .ap_ce(call_ret2_tpgPatternVerticalRa_fu_810_ap_ce)
);

hdmi_test_v_tpg_0_0_tpgPatternVerticalHo call_ret13_tpgPatternVerticalHo_fu_822(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ret13_tpgPatternVerticalHo_fu_822_ap_start),
    .ap_done(call_ret13_tpgPatternVerticalHo_fu_822_ap_done),
    .ap_idle(call_ret13_tpgPatternVerticalHo_fu_822_ap_idle),
    .ap_ready(call_ret13_tpgPatternVerticalHo_fu_822_ap_ready),
    .y(y_reg_453),
    .x(x_reg_465_pp0_iter4_reg),
    .rampStart(rampStart_load_reg_1390),
    .color(colorFormat),
    .ap_return_0(call_ret13_tpgPatternVerticalHo_fu_822_ap_return_0),
    .ap_return_1(call_ret13_tpgPatternVerticalHo_fu_822_ap_return_1),
    .ap_return_2(call_ret13_tpgPatternVerticalHo_fu_822_ap_return_2),
    .ap_ce(call_ret13_tpgPatternVerticalHo_fu_822_ap_ce)
);

hdmi_test_v_tpg_0_0_tpgPatternSolidBlue grp_tpgPatternSolidBlue_fu_834(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternSolidBlue_fu_834_ap_start),
    .ap_done(grp_tpgPatternSolidBlue_fu_834_ap_done),
    .ap_idle(grp_tpgPatternSolidBlue_fu_834_ap_idle),
    .ap_ready(grp_tpgPatternSolidBlue_fu_834_ap_ready),
    .ap_ce(grp_tpgPatternSolidBlue_fu_834_ap_ce),
    .x(x_reg_465_pp0_iter3_reg),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternSolidBlue_fu_834_ap_return_0),
    .ap_return_1(grp_tpgPatternSolidBlue_fu_834_ap_return_1),
    .ap_return_2(grp_tpgPatternSolidBlue_fu_834_ap_return_2)
);

hdmi_test_v_tpg_0_0_tpgPatternSolidGreen grp_tpgPatternSolidGreen_fu_843(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternSolidGreen_fu_843_ap_start),
    .ap_done(grp_tpgPatternSolidGreen_fu_843_ap_done),
    .ap_idle(grp_tpgPatternSolidGreen_fu_843_ap_idle),
    .ap_ready(grp_tpgPatternSolidGreen_fu_843_ap_ready),
    .ap_ce(grp_tpgPatternSolidGreen_fu_843_ap_ce),
    .x(x_reg_465_pp0_iter3_reg),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternSolidGreen_fu_843_ap_return_0),
    .ap_return_1(grp_tpgPatternSolidGreen_fu_843_ap_return_1),
    .ap_return_2(grp_tpgPatternSolidGreen_fu_843_ap_return_2)
);

hdmi_test_v_tpg_0_0_tpgPatternSolidRed grp_tpgPatternSolidRed_fu_852(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternSolidRed_fu_852_ap_start),
    .ap_done(grp_tpgPatternSolidRed_fu_852_ap_done),
    .ap_idle(grp_tpgPatternSolidRed_fu_852_ap_idle),
    .ap_ready(grp_tpgPatternSolidRed_fu_852_ap_ready),
    .ap_ce(grp_tpgPatternSolidRed_fu_852_ap_ce),
    .x(x_reg_465_pp0_iter3_reg),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternSolidRed_fu_852_ap_return_0),
    .ap_return_1(grp_tpgPatternSolidRed_fu_852_ap_return_1),
    .ap_return_2(grp_tpgPatternSolidRed_fu_852_ap_return_2)
);

hdmi_test_v_tpg_0_0_tpgPatternSolidWhite grp_tpgPatternSolidWhite_fu_861(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternSolidWhite_fu_861_ap_start),
    .ap_done(grp_tpgPatternSolidWhite_fu_861_ap_done),
    .ap_idle(grp_tpgPatternSolidWhite_fu_861_ap_idle),
    .ap_ready(grp_tpgPatternSolidWhite_fu_861_ap_ready),
    .ap_ce(grp_tpgPatternSolidWhite_fu_861_ap_ce),
    .x(x_reg_465_pp0_iter3_reg),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternSolidWhite_fu_861_ap_return_0),
    .ap_return_1(grp_tpgPatternSolidWhite_fu_861_ap_return_1)
);

hdmi_test_v_tpg_0_0_tpgPatternSolidBlack grp_tpgPatternSolidBlack_fu_870(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgPatternSolidBlack_fu_870_ap_start),
    .ap_done(grp_tpgPatternSolidBlack_fu_870_ap_done),
    .ap_idle(grp_tpgPatternSolidBlack_fu_870_ap_idle),
    .ap_ready(grp_tpgPatternSolidBlack_fu_870_ap_ready),
    .ap_ce(grp_tpgPatternSolidBlack_fu_870_ap_ce),
    .x(x_reg_465),
    .color(colorFormat),
    .ap_return_0(grp_tpgPatternSolidBlack_fu_870_ap_return_0),
    .ap_return_1(grp_tpgPatternSolidBlack_fu_870_ap_return_1)
);

hdmi_test_v_tpg_0_0_tpgPRBS call_ret15_tpgPRBS_fu_879(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ret15_tpgPRBS_fu_879_ap_start),
    .ap_done(call_ret15_tpgPRBS_fu_879_ap_done),
    .ap_idle(call_ret15_tpgPRBS_fu_879_ap_idle),
    .ap_ready(call_ret15_tpgPRBS_fu_879_ap_ready),
    .x(x_reg_465_pp0_iter4_reg),
    .color(colorFormat),
    .ap_return_0(call_ret15_tpgPRBS_fu_879_ap_return_0),
    .ap_return_1(call_ret15_tpgPRBS_fu_879_ap_return_1),
    .ap_return_2(call_ret15_tpgPRBS_fu_879_ap_return_2),
    .ap_ce(call_ret15_tpgPRBS_fu_879_ap_ce)
);

hdmi_test_v_tpg_0_0_tpgPatternHorizontal call_ret1_tpgPatternHorizontal_fu_892(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ret1_tpgPatternHorizontal_fu_892_ap_start),
    .ap_done(call_ret1_tpgPatternHorizontal_fu_892_ap_done),
    .ap_idle(call_ret1_tpgPatternHorizontal_fu_892_ap_idle),
    .ap_ready(call_ret1_tpgPatternHorizontal_fu_892_ap_ready),
    .x(x_reg_465_pp0_iter4_reg),
    .rampStart(rampStart_load_reg_1390),
    .color(colorFormat),
    .ap_return_0(call_ret1_tpgPatternHorizontal_fu_892_ap_return_0),
    .ap_return_1(call_ret1_tpgPatternHorizontal_fu_892_ap_return_1),
    .ap_return_2(call_ret1_tpgPatternHorizontal_fu_892_ap_return_2),
    .ap_ce(call_ret1_tpgPatternHorizontal_fu_892_ap_ce)
);

hdmi_test_v_tpg_0_0_tpgPatternTemporalRa call_ret3_tpgPatternTemporalRa_fu_902(
    .ap_ready(call_ret3_tpgPatternTemporalRa_fu_902_ap_ready),
    .rampStart(rampStart_load_reg_1390),
    .color(colorFormat),
    .ap_return_0(call_ret3_tpgPatternTemporalRa_fu_902_ap_return_0),
    .ap_return_1(call_ret3_tpgPatternTemporalRa_fu_902_ap_return_1),
    .ap_return_2(call_ret3_tpgPatternTemporalRa_fu_902_ap_return_2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((exitcond1_fu_942_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (exitcond2_fu_973_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond1_fu_942_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter6_state9)) | ((exitcond1_fu_942_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
            ap_enable_reg_pp0_iter6 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter6_state9))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter5;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end else if (((exitcond1_fu_942_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter7 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        call_ret13_tpgPatternVerticalHo_fu_822_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op117_call_state8_state7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            call_ret13_tpgPatternVerticalHo_fu_822_ap_start_reg <= 1'b1;
        end else if ((call_ret13_tpgPatternVerticalHo_fu_822_ap_ready == 1'b1)) begin
            call_ret13_tpgPatternVerticalHo_fu_822_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        call_ret15_tpgPRBS_fu_879_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op107_call_state8_state7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            call_ret15_tpgPRBS_fu_879_ap_start_reg <= 1'b1;
        end else if ((call_ret15_tpgPRBS_fu_879_ap_ready == 1'b1)) begin
            call_ret15_tpgPRBS_fu_879_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        call_ret1_tpgPatternHorizontal_fu_892_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op175_call_state8_state7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            call_ret1_tpgPatternHorizontal_fu_892_ap_start_reg <= 1'b1;
        end else if ((call_ret1_tpgPatternHorizontal_fu_892_ap_ready == 1'b1)) begin
            call_ret1_tpgPatternHorizontal_fu_892_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        call_ret2_tpgPatternVerticalRa_fu_810_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op170_call_state8_state7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            call_ret2_tpgPatternVerticalRa_fu_810_ap_start_reg <= 1'b1;
        end else if ((call_ret2_tpgPatternVerticalRa_fu_810_ap_ready == 1'b1)) begin
            call_ret2_tpgPatternVerticalRa_fu_810_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternCheckerBoa_fu_679_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op82_call_state6_state5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_tpgPatternCheckerBoa_fu_679_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternCheckerBoa_fu_679_ap_ready == 1'b1)) begin
            grp_tpgPatternCheckerBoa_fu_679_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternColorBars_fu_786_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter3 == 1'b1) & (ap_predicate_op99_call_state7_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_tpgPatternColorBars_fu_786_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternColorBars_fu_786_ap_ready == 1'b1)) begin
            grp_tpgPatternColorBars_fu_786_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternCrossHatch_fu_745_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter3 == 1'b1) & (ap_predicate_op96_call_state7_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_tpgPatternCrossHatch_fu_745_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternCrossHatch_fu_745_ap_ready == 1'b1)) begin
            grp_tpgPatternCrossHatch_fu_745_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternRainbow_fu_670_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op61_call_state4_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_tpgPatternRainbow_fu_670_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternRainbow_fu_670_ap_ready == 1'b1)) begin
            grp_tpgPatternRainbow_fu_670_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternSolidBlack_fu_870_ap_start_reg <= 1'b0;
    end else begin
        if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op63_call_state4_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op60_call_state4_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op59_call_state4_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op58_call_state4_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
            grp_tpgPatternSolidBlack_fu_870_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternSolidBlack_fu_870_ap_ready == 1'b1)) begin
            grp_tpgPatternSolidBlack_fu_870_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternSolidBlue_fu_834_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter3 == 1'b1) & (ap_predicate_op101_call_state7_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_tpgPatternSolidBlue_fu_834_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternSolidBlue_fu_834_ap_ready == 1'b1)) begin
            grp_tpgPatternSolidBlue_fu_834_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternSolidGreen_fu_843_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter3 == 1'b1) & (ap_predicate_op102_call_state7_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_tpgPatternSolidGreen_fu_843_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternSolidGreen_fu_843_ap_ready == 1'b1)) begin
            grp_tpgPatternSolidGreen_fu_843_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternSolidRed_fu_852_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter3 == 1'b1) & (ap_predicate_op103_call_state7_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_tpgPatternSolidRed_fu_852_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternSolidRed_fu_852_ap_ready == 1'b1)) begin
            grp_tpgPatternSolidRed_fu_852_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternSolidWhite_fu_861_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter3 == 1'b1) & (ap_predicate_op100_call_state7_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_tpgPatternSolidWhite_fu_861_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternSolidWhite_fu_861_ap_ready == 1'b1)) begin
            grp_tpgPatternSolidWhite_fu_861_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternTartanColo_fu_712_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op84_call_state6_state5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_tpgPatternTartanColo_fu_712_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternTartanColo_fu_712_ap_ready == 1'b1)) begin
            grp_tpgPatternTartanColo_fu_712_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgPatternZonePlate_fu_766_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op62_call_state4_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_tpgPatternZonePlate_fu_766_ap_start_reg <= 1'b1;
        end else if ((grp_tpgPatternZonePlate_fu_766_ap_ready == 1'b1)) begin
            grp_tpgPatternZonePlate_fu_766_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((exitcond2_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd7) & (1'b0 == ap_block_pp0_stage0_11001)) | ((exitcond2_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd17) & (1'b0 == ap_block_pp0_stage0_11001)) | ((exitcond2_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd18) & (1'b0 == ap_block_pp0_stage0_11001)) | ((exitcond2_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd19) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ap_phi_reg_pp0_iter3_outpix_val_V_0_2_reg_571 <= 8'd0;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_outpix_val_V_0_2_reg_571 <= ap_phi_reg_pp0_iter2_outpix_val_V_0_2_reg_571;
    end
end

always @ (posedge ap_clk) begin
    if ((((exitcond2_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd7) & (1'b0 == ap_block_pp0_stage0_11001)) | ((exitcond2_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd17) & (1'b0 == ap_block_pp0_stage0_11001)) | ((exitcond2_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd18) & (1'b0 == ap_block_pp0_stage0_11001)) | ((exitcond2_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd19) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ap_phi_reg_pp0_iter3_outpix_val_V_1_2_reg_524 <= grp_tpgPatternSolidBlack_fu_870_ap_return_0;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_outpix_val_V_1_2_reg_524 <= ap_phi_reg_pp0_iter2_outpix_val_V_1_2_reg_524;
    end
end

always @ (posedge ap_clk) begin
    if ((((exitcond2_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd7) & (1'b0 == ap_block_pp0_stage0_11001)) | ((exitcond2_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd17) & (1'b0 == ap_block_pp0_stage0_11001)) | ((exitcond2_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd18) & (1'b0 == ap_block_pp0_stage0_11001)) | ((exitcond2_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId == 8'd19) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ap_phi_reg_pp0_iter3_outpix_val_V_2_2_reg_477 <= grp_tpgPatternSolidBlack_fu_870_ap_return_1;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_outpix_val_V_2_2_reg_477 <= ap_phi_reg_pp0_iter2_outpix_val_V_2_2_reg_477;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId_read_read_fu_382_p2 == 8'd0))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_0_2_reg_571 <= outpix_val_0_V_fu_334;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd1))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_0_2_reg_571 <= call_ret1_tpgPatternHorizontal_fu_892_ap_return_0;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd2))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_0_2_reg_571 <= call_ret2_tpgPatternVerticalRa_fu_810_ap_return_0;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId_read_read_fu_382_p2 == 8'd3))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_0_2_reg_571 <= call_ret3_tpgPatternTemporalRa_fu_902_ap_return_0;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd4))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_0_2_reg_571 <= grp_tpgPatternSolidRed_fu_852_ap_return_0;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd5))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_0_2_reg_571 <= grp_tpgPatternSolidGreen_fu_843_ap_return_0;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd6))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_0_2_reg_571 <= grp_tpgPatternSolidBlue_fu_834_ap_return_0;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd8))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_0_2_reg_571 <= 8'd255;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd9))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_0_2_reg_571 <= grp_tpgPatternColorBars_fu_786_ap_return_0;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd11))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_0_2_reg_571 <= grp_tpgPatternTartanColo_fu_712_ap_return_0;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd12))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_0_2_reg_571 <= grp_tpgPatternCrossHatch_fu_745_ap_return_0;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd13))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_0_2_reg_571 <= grp_tpgPatternRainbow_fu_670_ap_return_0;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd14))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_0_2_reg_571 <= call_ret13_tpgPatternVerticalHo_fu_822_ap_return_0;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd15))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_0_2_reg_571 <= grp_tpgPatternCheckerBoa_fu_679_ap_return_0;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd16))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_0_2_reg_571 <= call_ret15_tpgPRBS_fu_879_ap_return_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_0_2_reg_571 <= ap_phi_reg_pp0_iter5_outpix_val_V_0_2_reg_571;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId_read_read_fu_382_p2 == 8'd0))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_1_2_reg_524 <= outpix_val_1_V_fu_338;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd1))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_1_2_reg_524 <= call_ret1_tpgPatternHorizontal_fu_892_ap_return_1;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd2))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_1_2_reg_524 <= call_ret2_tpgPatternVerticalRa_fu_810_ap_return_1;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId_read_read_fu_382_p2 == 8'd3))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_1_2_reg_524 <= call_ret3_tpgPatternTemporalRa_fu_902_ap_return_1;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd4))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_1_2_reg_524 <= grp_tpgPatternSolidRed_fu_852_ap_return_1;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd5))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_1_2_reg_524 <= grp_tpgPatternSolidGreen_fu_843_ap_return_1;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd6))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_1_2_reg_524 <= grp_tpgPatternSolidBlue_fu_834_ap_return_1;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd8))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_1_2_reg_524 <= grp_tpgPatternSolidWhite_fu_861_ap_return_0;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd9))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_1_2_reg_524 <= grp_tpgPatternColorBars_fu_786_ap_return_1;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd11))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_1_2_reg_524 <= grp_tpgPatternTartanColo_fu_712_ap_return_1;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd12))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_1_2_reg_524 <= grp_tpgPatternCrossHatch_fu_745_ap_return_1;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd13))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_1_2_reg_524 <= grp_tpgPatternRainbow_fu_670_ap_return_1;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd14))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_1_2_reg_524 <= call_ret13_tpgPatternVerticalHo_fu_822_ap_return_1;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd15))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_1_2_reg_524 <= grp_tpgPatternCheckerBoa_fu_679_ap_return_1;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd16))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_1_2_reg_524 <= call_ret15_tpgPRBS_fu_879_ap_return_1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_1_2_reg_524 <= ap_phi_reg_pp0_iter5_outpix_val_V_1_2_reg_524;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId_read_read_fu_382_p2 == 8'd0))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_2_2_reg_477 <= outpix_val_2_V_fu_342;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd1))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_2_2_reg_477 <= call_ret1_tpgPatternHorizontal_fu_892_ap_return_2;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd2))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_2_2_reg_477 <= call_ret2_tpgPatternVerticalRa_fu_810_ap_return_2;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId_read_read_fu_382_p2 == 8'd3))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_2_2_reg_477 <= call_ret3_tpgPatternTemporalRa_fu_902_ap_return_2;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd4))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_2_2_reg_477 <= grp_tpgPatternSolidRed_fu_852_ap_return_2;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd5))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_2_2_reg_477 <= grp_tpgPatternSolidGreen_fu_843_ap_return_2;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd6))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_2_2_reg_477 <= grp_tpgPatternSolidBlue_fu_834_ap_return_2;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd8))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_2_2_reg_477 <= grp_tpgPatternSolidWhite_fu_861_ap_return_1;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd9))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_2_2_reg_477 <= grp_tpgPatternColorBars_fu_786_ap_return_2;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd11))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_2_2_reg_477 <= grp_tpgPatternTartanColo_fu_712_ap_return_2;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd12))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_2_2_reg_477 <= grp_tpgPatternCrossHatch_fu_745_ap_return_2;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd13))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_2_2_reg_477 <= grp_tpgPatternRainbow_fu_670_ap_return_2;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd14))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_2_2_reg_477 <= call_ret13_tpgPatternVerticalHo_fu_822_ap_return_2;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd15))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_2_2_reg_477 <= grp_tpgPatternCheckerBoa_fu_679_ap_return_2;
        end else if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd16))) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_2_2_reg_477 <= call_ret15_tpgPRBS_fu_879_ap_return_2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter6_outpix_val_V_2_2_reg_477 <= ap_phi_reg_pp0_iter5_outpix_val_V_2_2_reg_477;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_932_p2 == 1'd0) & (or_cond_reg_1428_pp0_iter5_reg == 1'd0) & (exitcond2_reg_1419_pp0_iter5_reg == 1'd0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_val_0_V_2_reg_655 <= pix_val_V_0_2_outpix_fu_1242_p3;
    end else if ((((tmp_fu_932_p2 == 1'd0) & (exitcond2_reg_1419_pp0_iter5_reg == 1'd0) & (or_cond_reg_1428_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_fu_932_p2 == 1'd1) & (exitcond2_reg_1419_pp0_iter5_reg == 1'd0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        tmp_val_0_V_2_reg_655 <= ap_phi_mux_outpix_val_V_0_2_phi_fu_576_p42;
    end else if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_val_0_V_2_reg_655 <= ap_phi_reg_pp0_iter6_tmp_val_0_V_2_reg_655;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_932_p2 == 1'd0) & (or_cond_reg_1428_pp0_iter5_reg == 1'd0) & (exitcond2_reg_1419_pp0_iter5_reg == 1'd0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_val_1_V_2_reg_640 <= pix_val_V_1_2_outpix_fu_1235_p3;
    end else if ((((tmp_fu_932_p2 == 1'd0) & (exitcond2_reg_1419_pp0_iter5_reg == 1'd0) & (or_cond_reg_1428_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_fu_932_p2 == 1'd1) & (exitcond2_reg_1419_pp0_iter5_reg == 1'd0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        tmp_val_1_V_2_reg_640 <= ap_phi_mux_outpix_val_V_1_2_phi_fu_527_p42;
    end else if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_val_1_V_2_reg_640 <= ap_phi_reg_pp0_iter6_tmp_val_1_V_2_reg_640;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_932_p2 == 1'd0) & (or_cond_reg_1428_pp0_iter5_reg == 1'd0) & (exitcond2_reg_1419_pp0_iter5_reg == 1'd0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_val_2_V_2_reg_625 <= pix_val_V_2_2_outpix_fu_1228_p3;
    end else if ((((tmp_fu_932_p2 == 1'd0) & (exitcond2_reg_1419_pp0_iter5_reg == 1'd0) & (or_cond_reg_1428_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_fu_932_p2 == 1'd1) & (exitcond2_reg_1419_pp0_iter5_reg == 1'd0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        tmp_val_2_V_2_reg_625 <= ap_phi_mux_outpix_val_V_2_2_phi_fu_480_p42;
    end else if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_val_2_V_2_reg_625 <= ap_phi_reg_pp0_iter6_tmp_val_2_V_2_reg_625;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_reg_1419 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_reg_465 <= x_1_reg_1423;
    end else if (((exitcond1_fu_942_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        x_reg_465 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        y_reg_453 <= y_1_reg_1404;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_reg_453 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_outpix_val_V_0_2_reg_571 <= ap_phi_reg_pp0_iter0_outpix_val_V_0_2_reg_571;
        ap_phi_reg_pp0_iter1_outpix_val_V_1_2_reg_524 <= ap_phi_reg_pp0_iter0_outpix_val_V_1_2_reg_524;
        ap_phi_reg_pp0_iter1_outpix_val_V_2_2_reg_477 <= ap_phi_reg_pp0_iter0_outpix_val_V_2_2_reg_477;
        x_1_reg_1423 <= x_1_fu_978_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter2_outpix_val_V_0_2_reg_571 <= ap_phi_reg_pp0_iter1_outpix_val_V_0_2_reg_571;
        ap_phi_reg_pp0_iter2_outpix_val_V_1_2_reg_524 <= ap_phi_reg_pp0_iter1_outpix_val_V_1_2_reg_524;
        ap_phi_reg_pp0_iter2_outpix_val_V_2_2_reg_477 <= ap_phi_reg_pp0_iter1_outpix_val_V_2_2_reg_477;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571 <= ap_phi_reg_pp0_iter3_outpix_val_V_0_2_reg_571;
        ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524 <= ap_phi_reg_pp0_iter3_outpix_val_V_1_2_reg_524;
        ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477 <= ap_phi_reg_pp0_iter3_outpix_val_V_2_2_reg_477;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter5_outpix_val_V_0_2_reg_571 <= ap_phi_reg_pp0_iter4_outpix_val_V_0_2_reg_571;
        ap_phi_reg_pp0_iter5_outpix_val_V_1_2_reg_524 <= ap_phi_reg_pp0_iter4_outpix_val_V_1_2_reg_524;
        ap_phi_reg_pp0_iter5_outpix_val_V_2_2_reg_477 <= ap_phi_reg_pp0_iter4_outpix_val_V_2_2_reg_477;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond2_reg_1419 <= exitcond2_fu_973_p2;
        exitcond2_reg_1419_pp0_iter1_reg <= exitcond2_reg_1419;
        or_cond2_reg_1432_pp0_iter1_reg <= or_cond2_reg_1432;
        or_cond_reg_1428_pp0_iter1_reg <= or_cond_reg_1428;
        x_reg_465_pp0_iter1_reg <= x_reg_465;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        exitcond2_reg_1419_pp0_iter2_reg <= exitcond2_reg_1419_pp0_iter1_reg;
        exitcond2_reg_1419_pp0_iter3_reg <= exitcond2_reg_1419_pp0_iter2_reg;
        exitcond2_reg_1419_pp0_iter4_reg <= exitcond2_reg_1419_pp0_iter3_reg;
        exitcond2_reg_1419_pp0_iter5_reg <= exitcond2_reg_1419_pp0_iter4_reg;
        exitcond2_reg_1419_pp0_iter6_reg <= exitcond2_reg_1419_pp0_iter5_reg;
        or_cond2_reg_1432_pp0_iter2_reg <= or_cond2_reg_1432_pp0_iter1_reg;
        or_cond2_reg_1432_pp0_iter3_reg <= or_cond2_reg_1432_pp0_iter2_reg;
        or_cond2_reg_1432_pp0_iter4_reg <= or_cond2_reg_1432_pp0_iter3_reg;
        or_cond2_reg_1432_pp0_iter5_reg <= or_cond2_reg_1432_pp0_iter4_reg;
        or_cond_reg_1428_pp0_iter2_reg <= or_cond_reg_1428_pp0_iter1_reg;
        or_cond_reg_1428_pp0_iter3_reg <= or_cond_reg_1428_pp0_iter2_reg;
        or_cond_reg_1428_pp0_iter4_reg <= or_cond_reg_1428_pp0_iter3_reg;
        or_cond_reg_1428_pp0_iter5_reg <= or_cond_reg_1428_pp0_iter4_reg;
        x_reg_465_pp0_iter2_reg <= x_reg_465_pp0_iter1_reg;
        x_reg_465_pp0_iter3_reg <= x_reg_465_pp0_iter2_reg;
        x_reg_465_pp0_iter4_reg <= x_reg_465_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_932_p2 == 1'd0) & (or_cond_fu_989_p2 == 1'd0) & (exitcond2_fu_973_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        or_cond2_reg_1432 <= or_cond2_fu_999_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_932_p2 == 1'd0) & (exitcond2_fu_973_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        or_cond_reg_1428 <= or_cond_fu_989_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outpix_val_0_V_15_reg_1439 <= outpix_val_0_V_fu_334;
        outpix_val_1_V_20_reg_1445 <= outpix_val_1_V_fu_338;
        outpix_val_2_V_20_reg_1451 <= outpix_val_2_V_fu_342;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd10) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outpix_val_0_V_8_reg_1547 <= grp_tpgPatternZonePlate_fu_766_ap_return_0;
        outpix_val_1_V_21_reg_1552 <= grp_tpgPatternZonePlate_fu_766_ap_return_1;
        outpix_val_2_V_21_reg_1557 <= grp_tpgPatternZonePlate_fu_766_ap_return_2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_932_p2 == 1'd0) & (exitcond2_reg_1419_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outpix_val_0_V_fu_334 <= srcImg_V_val_0_V_dout;
        outpix_val_1_V_fu_338 <= srcImg_V_val_1_V_dout;
        outpix_val_2_V_fu_342 <= srcImg_V_val_2_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_942_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        rampStart <= tmp_s_fu_963_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampStart_load_reg_1390 <= rampStart;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_942_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_84_reg_1409 <= tmp_84_fu_953_p2;
        tmp_85_reg_1414 <= tmp_85_fu_958_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_reg_1419_pp0_iter5_reg == 1'd0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_val_0_V_fu_322 <= ap_phi_mux_tmp_val_0_V_2_phi_fu_659_p6;
        tmp_val_1_V_fu_326 <= ap_phi_mux_tmp_val_1_V_2_phi_fu_644_p6;
        tmp_val_2_V_fu_330 <= ap_phi_mux_tmp_val_2_V_2_phi_fu_629_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        y_1_reg_1404 <= y_1_fu_947_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b0))) begin
        ap_condition_pp0_exit_iter6_state9 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter6_state9 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_fu_942_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1830)) begin
        if ((patternId == 8'd10)) begin
            ap_phi_mux_outpix_val_V_0_2_phi_fu_576_p42 = outpix_val_0_V_8_reg_1547;
        end else if ((1'b1 == ap_condition_1849)) begin
            ap_phi_mux_outpix_val_V_0_2_phi_fu_576_p42 = tmp_val_0_V_fu_322;
        end else begin
            ap_phi_mux_outpix_val_V_0_2_phi_fu_576_p42 = ap_phi_reg_pp0_iter6_outpix_val_V_0_2_reg_571;
        end
    end else begin
        ap_phi_mux_outpix_val_V_0_2_phi_fu_576_p42 = ap_phi_reg_pp0_iter6_outpix_val_V_0_2_reg_571;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1830)) begin
        if ((patternId == 8'd10)) begin
            ap_phi_mux_outpix_val_V_1_2_phi_fu_527_p42 = outpix_val_1_V_21_reg_1552;
        end else if ((1'b1 == ap_condition_1849)) begin
            ap_phi_mux_outpix_val_V_1_2_phi_fu_527_p42 = tmp_val_1_V_fu_326;
        end else begin
            ap_phi_mux_outpix_val_V_1_2_phi_fu_527_p42 = ap_phi_reg_pp0_iter6_outpix_val_V_1_2_reg_524;
        end
    end else begin
        ap_phi_mux_outpix_val_V_1_2_phi_fu_527_p42 = ap_phi_reg_pp0_iter6_outpix_val_V_1_2_reg_524;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1830)) begin
        if ((patternId == 8'd10)) begin
            ap_phi_mux_outpix_val_V_2_2_phi_fu_480_p42 = outpix_val_2_V_21_reg_1557;
        end else if ((1'b1 == ap_condition_1849)) begin
            ap_phi_mux_outpix_val_V_2_2_phi_fu_480_p42 = tmp_val_2_V_fu_330;
        end else begin
            ap_phi_mux_outpix_val_V_2_2_phi_fu_480_p42 = ap_phi_reg_pp0_iter6_outpix_val_V_2_2_reg_477;
        end
    end else begin
        ap_phi_mux_outpix_val_V_2_2_phi_fu_480_p42 = ap_phi_reg_pp0_iter6_outpix_val_V_2_2_reg_477;
    end
end

always @ (*) begin
    if (((tmp_fu_932_p2 == 1'd0) & (or_cond_reg_1428_pp0_iter5_reg == 1'd0) & (exitcond2_reg_1419_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_phi_mux_tmp_val_0_V_2_phi_fu_659_p6 = pix_val_V_0_2_outpix_fu_1242_p3;
    end else if ((((tmp_fu_932_p2 == 1'd0) & (exitcond2_reg_1419_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (or_cond_reg_1428_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((tmp_fu_932_p2 == 1'd1) & (exitcond2_reg_1419_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1)))) begin
        ap_phi_mux_tmp_val_0_V_2_phi_fu_659_p6 = ap_phi_mux_outpix_val_V_0_2_phi_fu_576_p42;
    end else begin
        ap_phi_mux_tmp_val_0_V_2_phi_fu_659_p6 = ap_phi_reg_pp0_iter6_tmp_val_0_V_2_reg_655;
    end
end

always @ (*) begin
    if (((tmp_fu_932_p2 == 1'd0) & (or_cond_reg_1428_pp0_iter5_reg == 1'd0) & (exitcond2_reg_1419_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_phi_mux_tmp_val_1_V_2_phi_fu_644_p6 = pix_val_V_1_2_outpix_fu_1235_p3;
    end else if ((((tmp_fu_932_p2 == 1'd0) & (exitcond2_reg_1419_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (or_cond_reg_1428_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((tmp_fu_932_p2 == 1'd1) & (exitcond2_reg_1419_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1)))) begin
        ap_phi_mux_tmp_val_1_V_2_phi_fu_644_p6 = ap_phi_mux_outpix_val_V_1_2_phi_fu_527_p42;
    end else begin
        ap_phi_mux_tmp_val_1_V_2_phi_fu_644_p6 = ap_phi_reg_pp0_iter6_tmp_val_1_V_2_reg_640;
    end
end

always @ (*) begin
    if (((tmp_fu_932_p2 == 1'd0) & (or_cond_reg_1428_pp0_iter5_reg == 1'd0) & (exitcond2_reg_1419_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_phi_mux_tmp_val_2_V_2_phi_fu_629_p6 = pix_val_V_2_2_outpix_fu_1228_p3;
    end else if ((((tmp_fu_932_p2 == 1'd0) & (exitcond2_reg_1419_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (or_cond_reg_1428_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((tmp_fu_932_p2 == 1'd1) & (exitcond2_reg_1419_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1)))) begin
        ap_phi_mux_tmp_val_2_V_2_phi_fu_629_p6 = ap_phi_mux_outpix_val_V_2_2_phi_fu_480_p42;
    end else begin
        ap_phi_mux_tmp_val_2_V_2_phi_fu_629_p6 = ap_phi_reg_pp0_iter6_tmp_val_2_V_2_reg_625;
    end
end

always @ (*) begin
    if (((exitcond2_reg_1419 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_x_phi_fu_469_p4 = x_1_reg_1423;
    end else begin
        ap_phi_mux_x_phi_fu_469_p4 = x_reg_465;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp117) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        call_ret13_tpgPatternVerticalHo_fu_822_ap_ce = 1'b1;
    end else begin
        call_ret13_tpgPatternVerticalHo_fu_822_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp107) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        call_ret15_tpgPRBS_fu_879_ap_ce = 1'b1;
    end else begin
        call_ret15_tpgPRBS_fu_879_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp175) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        call_ret1_tpgPatternHorizontal_fu_892_ap_ce = 1'b1;
    end else begin
        call_ret1_tpgPatternHorizontal_fu_892_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp170) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        call_ret2_tpgPatternVerticalRa_fu_810_ap_ce = 1'b1;
    end else begin
        call_ret2_tpgPatternVerticalRa_fu_810_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp82) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternCheckerBoa_fu_679_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternCheckerBoa_fu_679_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp99) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternColorBars_fu_786_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternColorBars_fu_786_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp96) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternCrossHatch_fu_745_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternCrossHatch_fu_745_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp61) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternRainbow_fu_670_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternRainbow_fu_670_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp58) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternSolidBlack_fu_870_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternSolidBlack_fu_870_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp101) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternSolidBlue_fu_834_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternSolidBlue_fu_834_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp102) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternSolidGreen_fu_843_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternSolidGreen_fu_843_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp103) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternSolidRed_fu_852_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternSolidRed_fu_852_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp100) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternSolidWhite_fu_861_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternSolidWhite_fu_861_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp84) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternTartanColo_fu_712_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternTartanColo_fu_712_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp62) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_tpgPatternZonePlate_fu_766_ap_ce = 1'b1;
    end else begin
        grp_tpgPatternZonePlate_fu_766_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_fu_942_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outImg_V_val_0_V1_update = 1'b1;
    end else begin
        outImg_V_val_0_V1_update = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        outImg_V_val_0_V_blk_n = outImg_V_val_0_V_full_n;
    end else begin
        outImg_V_val_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        outImg_V_val_1_V_blk_n = outImg_V_val_1_V_full_n;
    end else begin
        outImg_V_val_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        outImg_V_val_2_V_blk_n = outImg_V_val_2_V_full_n;
    end else begin
        outImg_V_val_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op86_read_state7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        srcImg_V_val_0_V0_update = 1'b1;
    end else begin
        srcImg_V_val_0_V0_update = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_932_p2 == 1'd0) & (exitcond2_reg_1419_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        srcImg_V_val_0_V_blk_n = srcImg_V_val_0_V_empty_n;
    end else begin
        srcImg_V_val_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_fu_932_p2 == 1'd0) & (exitcond2_reg_1419_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        srcImg_V_val_1_V_blk_n = srcImg_V_val_1_V_empty_n;
    end else begin
        srcImg_V_val_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_fu_932_p2 == 1'd0) & (exitcond2_reg_1419_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        srcImg_V_val_2_V_blk_n = srcImg_V_val_2_V_empty_n;
    end else begin
        srcImg_V_val_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond1_fu_942_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter5 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter5 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op86_read_state7 == 1'b1)) | ((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op86_read_state7 == 1'b1)) | ((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp100 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op86_read_state7 == 1'b1)) | ((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp101 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op86_read_state7 == 1'b1)) | ((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp102 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op86_read_state7 == 1'b1)) | ((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp103 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op86_read_state7 == 1'b1)) | ((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp107 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op86_read_state7 == 1'b1)) | ((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp117 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op86_read_state7 == 1'b1)) | ((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp170 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op86_read_state7 == 1'b1)) | ((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp175 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op86_read_state7 == 1'b1)) | ((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp58 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op86_read_state7 == 1'b1)) | ((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp61 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op86_read_state7 == 1'b1)) | ((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp62 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op86_read_state7 == 1'b1)) | ((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp82 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op86_read_state7 == 1'b1)) | ((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp84 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op86_read_state7 == 1'b1)) | ((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp96 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op86_read_state7 == 1'b1)) | ((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp99 = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op86_read_state7 == 1'b1)) | ((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((srcImg_V_val_0_V0_status == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op86_read_state7 == 1'b1)) | ((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter7 = ((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter7_ignore_call0 = ((exitcond2_reg_1419_pp0_iter6_reg == 1'd0) & (outImg_V_val_0_V1_status == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter3_ignore_call0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter4 = ((srcImg_V_val_0_V0_status == 1'b0) & (ap_predicate_op86_read_state7 == 1'b1));
end

always @ (*) begin
    ap_block_state7_pp0_stage0_iter4_ignore_call0 = ((srcImg_V_val_0_V0_status == 1'b0) & (ap_predicate_op86_read_state7 == 1'b1));
end

assign ap_block_state8_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter5_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter6_ignore_call0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1830 = ((exitcond2_reg_1419_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_condition_1849 = (~(patternId_read_read_fu_382_p2 == 8'd0) & ~(patternId == 8'd1) & ~(patternId == 8'd2) & ~(patternId_read_read_fu_382_p2 == 8'd3) & ~(patternId == 8'd4) & ~(patternId == 8'd5) & ~(patternId == 8'd6) & ~(patternId == 8'd8) & ~(patternId == 8'd9) & ~(patternId == 8'd10) & ~(patternId == 8'd11) & ~(patternId == 8'd12) & ~(patternId == 8'd13) & ~(patternId == 8'd14) & ~(patternId == 8'd15) & ~(patternId == 8'd16) & ~(patternId == 8'd7) & ~(patternId == 8'd17) & ~(patternId == 8'd18) & ~(patternId == 8'd19));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_outpix_val_V_0_2_reg_571 = 'bx;

assign ap_phi_reg_pp0_iter0_outpix_val_V_1_2_reg_524 = 'bx;

assign ap_phi_reg_pp0_iter0_outpix_val_V_2_2_reg_477 = 'bx;

assign ap_phi_reg_pp0_iter6_tmp_val_0_V_2_reg_655 = 'bx;

assign ap_phi_reg_pp0_iter6_tmp_val_1_V_2_reg_640 = 'bx;

assign ap_phi_reg_pp0_iter6_tmp_val_2_V_2_reg_625 = 'bx;

always @ (*) begin
    ap_predicate_op100_call_state7 = ((exitcond2_reg_1419_pp0_iter3_reg == 1'd0) & (patternId == 8'd8));
end

always @ (*) begin
    ap_predicate_op100_call_state7_state6 = ((exitcond2_reg_1419_pp0_iter2_reg == 1'd0) & (patternId == 8'd8));
end

always @ (*) begin
    ap_predicate_op101_call_state7 = ((exitcond2_reg_1419_pp0_iter3_reg == 1'd0) & (patternId == 8'd6));
end

always @ (*) begin
    ap_predicate_op101_call_state7_state6 = ((exitcond2_reg_1419_pp0_iter2_reg == 1'd0) & (patternId == 8'd6));
end

always @ (*) begin
    ap_predicate_op102_call_state7 = ((exitcond2_reg_1419_pp0_iter3_reg == 1'd0) & (patternId == 8'd5));
end

always @ (*) begin
    ap_predicate_op102_call_state7_state6 = ((exitcond2_reg_1419_pp0_iter2_reg == 1'd0) & (patternId == 8'd5));
end

always @ (*) begin
    ap_predicate_op103_call_state7 = ((exitcond2_reg_1419_pp0_iter3_reg == 1'd0) & (patternId == 8'd4));
end

always @ (*) begin
    ap_predicate_op103_call_state7_state6 = ((exitcond2_reg_1419_pp0_iter2_reg == 1'd0) & (patternId == 8'd4));
end

always @ (*) begin
    ap_predicate_op107_call_state8 = ((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd16));
end

always @ (*) begin
    ap_predicate_op107_call_state8_state7 = ((exitcond2_reg_1419_pp0_iter3_reg == 1'd0) & (patternId == 8'd16));
end

always @ (*) begin
    ap_predicate_op117_call_state8 = ((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd14));
end

always @ (*) begin
    ap_predicate_op117_call_state8_state7 = ((exitcond2_reg_1419_pp0_iter3_reg == 1'd0) & (patternId == 8'd14));
end

always @ (*) begin
    ap_predicate_op170_call_state8 = ((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd2));
end

always @ (*) begin
    ap_predicate_op170_call_state8_state7 = ((exitcond2_reg_1419_pp0_iter3_reg == 1'd0) & (patternId == 8'd2));
end

always @ (*) begin
    ap_predicate_op175_call_state8 = ((exitcond2_reg_1419_pp0_iter4_reg == 1'd0) & (patternId == 8'd1));
end

always @ (*) begin
    ap_predicate_op175_call_state8_state7 = ((exitcond2_reg_1419_pp0_iter3_reg == 1'd0) & (patternId == 8'd1));
end

always @ (*) begin
    ap_predicate_op58_call_state4 = ((exitcond2_reg_1419 == 1'd0) & (patternId == 8'd19));
end

always @ (*) begin
    ap_predicate_op58_call_state4_state3 = ((exitcond2_fu_973_p2 == 1'd0) & (patternId == 8'd19));
end

always @ (*) begin
    ap_predicate_op59_call_state4 = ((exitcond2_reg_1419 == 1'd0) & (patternId == 8'd18));
end

always @ (*) begin
    ap_predicate_op59_call_state4_state3 = ((exitcond2_fu_973_p2 == 1'd0) & (patternId == 8'd18));
end

always @ (*) begin
    ap_predicate_op60_call_state4 = ((exitcond2_reg_1419 == 1'd0) & (patternId == 8'd17));
end

always @ (*) begin
    ap_predicate_op60_call_state4_state3 = ((exitcond2_fu_973_p2 == 1'd0) & (patternId == 8'd17));
end

always @ (*) begin
    ap_predicate_op61_call_state4 = ((exitcond2_reg_1419 == 1'd0) & (patternId == 8'd13));
end

always @ (*) begin
    ap_predicate_op61_call_state4_state3 = ((exitcond2_fu_973_p2 == 1'd0) & (patternId == 8'd13));
end

always @ (*) begin
    ap_predicate_op62_call_state4 = ((exitcond2_reg_1419 == 1'd0) & (patternId == 8'd10));
end

always @ (*) begin
    ap_predicate_op62_call_state4_state3 = ((exitcond2_fu_973_p2 == 1'd0) & (patternId == 8'd10));
end

always @ (*) begin
    ap_predicate_op63_call_state4 = ((exitcond2_reg_1419 == 1'd0) & (patternId == 8'd7));
end

always @ (*) begin
    ap_predicate_op63_call_state4_state3 = ((exitcond2_fu_973_p2 == 1'd0) & (patternId == 8'd7));
end

always @ (*) begin
    ap_predicate_op82_call_state6 = ((exitcond2_reg_1419_pp0_iter2_reg == 1'd0) & (patternId == 8'd15));
end

always @ (*) begin
    ap_predicate_op82_call_state6_state5 = ((exitcond2_reg_1419_pp0_iter1_reg == 1'd0) & (patternId == 8'd15));
end

always @ (*) begin
    ap_predicate_op84_call_state6 = ((exitcond2_reg_1419_pp0_iter2_reg == 1'd0) & (patternId == 8'd11));
end

always @ (*) begin
    ap_predicate_op84_call_state6_state5 = ((exitcond2_reg_1419_pp0_iter1_reg == 1'd0) & (patternId == 8'd11));
end

always @ (*) begin
    ap_predicate_op86_read_state7 = ((tmp_fu_932_p2 == 1'd0) & (exitcond2_reg_1419_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op96_call_state7 = ((exitcond2_reg_1419_pp0_iter3_reg == 1'd0) & (patternId == 8'd12));
end

always @ (*) begin
    ap_predicate_op96_call_state7_state6 = ((exitcond2_reg_1419_pp0_iter2_reg == 1'd0) & (patternId == 8'd12));
end

always @ (*) begin
    ap_predicate_op99_call_state7 = ((exitcond2_reg_1419_pp0_iter3_reg == 1'd0) & (patternId == 8'd9));
end

always @ (*) begin
    ap_predicate_op99_call_state7_state6 = ((exitcond2_reg_1419_pp0_iter2_reg == 1'd0) & (patternId == 8'd9));
end

assign ap_ready = internal_ap_ready;

assign call_ret13_tpgPatternVerticalHo_fu_822_ap_start = call_ret13_tpgPatternVerticalHo_fu_822_ap_start_reg;

assign call_ret15_tpgPRBS_fu_879_ap_start = call_ret15_tpgPRBS_fu_879_ap_start_reg;

assign call_ret1_tpgPatternHorizontal_fu_892_ap_start = call_ret1_tpgPatternHorizontal_fu_892_ap_start_reg;

assign call_ret2_tpgPatternVerticalRa_fu_810_ap_start = call_ret2_tpgPatternVerticalRa_fu_810_ap_start_reg;

assign exitcond1_fu_942_p2 = ((y_reg_453 == height) ? 1'b1 : 1'b0);

assign exitcond2_fu_973_p2 = ((ap_phi_mux_x_phi_fu_469_p4 == width) ? 1'b1 : 1'b0);

assign grp_tpgPatternCheckerBoa_fu_679_ap_start = grp_tpgPatternCheckerBoa_fu_679_ap_start_reg;

assign grp_tpgPatternColorBars_fu_786_ap_start = grp_tpgPatternColorBars_fu_786_ap_start_reg;

assign grp_tpgPatternCrossHatch_fu_745_ap_start = grp_tpgPatternCrossHatch_fu_745_ap_start_reg;

assign grp_tpgPatternRainbow_fu_670_ap_start = grp_tpgPatternRainbow_fu_670_ap_start_reg;

assign grp_tpgPatternSolidBlack_fu_870_ap_start = grp_tpgPatternSolidBlack_fu_870_ap_start_reg;

assign grp_tpgPatternSolidBlue_fu_834_ap_start = grp_tpgPatternSolidBlue_fu_834_ap_start_reg;

assign grp_tpgPatternSolidGreen_fu_843_ap_start = grp_tpgPatternSolidGreen_fu_843_ap_start_reg;

assign grp_tpgPatternSolidRed_fu_852_ap_start = grp_tpgPatternSolidRed_fu_852_ap_start_reg;

assign grp_tpgPatternSolidWhite_fu_861_ap_start = grp_tpgPatternSolidWhite_fu_861_ap_start_reg;

assign grp_tpgPatternTartanColo_fu_712_ap_start = grp_tpgPatternTartanColo_fu_712_ap_start_reg;

assign grp_tpgPatternZonePlate_fu_766_ap_start = grp_tpgPatternZonePlate_fu_766_ap_start_reg;

assign or_cond2_fu_999_p2 = (tmp_92_fu_994_p2 & tmp_85_reg_1414);

assign or_cond_fu_989_p2 = (tmp_91_fu_984_p2 | tmp_84_reg_1409);

assign outImg_V_val_0_V1_status = (outImg_V_val_2_V_full_n & outImg_V_val_1_V_full_n & outImg_V_val_0_V_full_n);

assign outImg_V_val_0_V_din = tmp_val_0_V_2_reg_655;

assign outImg_V_val_0_V_write = outImg_V_val_0_V1_update;

assign outImg_V_val_1_V_din = tmp_val_1_V_2_reg_640;

assign outImg_V_val_1_V_write = outImg_V_val_0_V1_update;

assign outImg_V_val_2_V_din = tmp_val_2_V_2_reg_625;

assign outImg_V_val_2_V_write = outImg_V_val_0_V1_update;

assign patternId_read_read_fu_382_p2 = patternId;

assign pix_val_V_0_2_outpix_fu_1242_p3 = ((or_cond2_reg_1432_pp0_iter5_reg[0:0] === 1'b1) ? outpix_val_0_V_15_reg_1439 : ap_phi_mux_outpix_val_V_0_2_phi_fu_576_p42);

assign pix_val_V_1_2_outpix_fu_1235_p3 = ((or_cond2_reg_1432_pp0_iter5_reg[0:0] === 1'b1) ? outpix_val_1_V_20_reg_1445 : ap_phi_mux_outpix_val_V_1_2_phi_fu_527_p42);

assign pix_val_V_2_2_outpix_fu_1228_p3 = ((or_cond2_reg_1432_pp0_iter5_reg[0:0] === 1'b1) ? outpix_val_2_V_20_reg_1451 : ap_phi_mux_outpix_val_V_2_2_phi_fu_480_p42);

assign srcImg_V_val_0_V0_status = (srcImg_V_val_2_V_empty_n & srcImg_V_val_1_V_empty_n & srcImg_V_val_0_V_empty_n);

assign srcImg_V_val_0_V_read = srcImg_V_val_0_V0_update;

assign srcImg_V_val_1_V_read = srcImg_V_val_0_V0_update;

assign srcImg_V_val_2_V_read = srcImg_V_val_0_V0_update;

assign start_out = real_start;

assign tmp_84_fu_953_p2 = ((y_reg_453 < passthruStartY) ? 1'b1 : 1'b0);

assign tmp_85_fu_958_p2 = ((y_reg_453 < passthruEndY) ? 1'b1 : 1'b0);

assign tmp_91_fu_984_p2 = ((ap_phi_mux_x_phi_fu_469_p4 < passthruStartX) ? 1'b1 : 1'b0);

assign tmp_92_fu_994_p2 = ((ap_phi_mux_x_phi_fu_469_p4 < passthruEndX) ? 1'b1 : 1'b0);

assign tmp_fu_932_p2 = ((enableInput == 8'd0) ? 1'b1 : 1'b0);

assign tmp_s_fu_963_p2 = (rampStart_load_reg_1390 + motionSpeed);

assign x_1_fu_978_p2 = (ap_phi_mux_x_phi_fu_469_p4 + 16'd1);

assign y_1_fu_947_p2 = (y_reg_453 + 16'd1);

endmodule //hdmi_test_v_tpg_0_0_tpgBackground
